/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_udp/msg/E_LIMITS_STATE.msg
 *
 */


#ifndef MAVLINK_UDP_MESSAGE_E_LIMITS_STATE_H
#define MAVLINK_UDP_MESSAGE_E_LIMITS_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_udp
{
template <class ContainerAllocator>
struct E_LIMITS_STATE_
{
  typedef E_LIMITS_STATE_<ContainerAllocator> Type;

  E_LIMITS_STATE_()
    {
    }
  E_LIMITS_STATE_(const ContainerAllocator& _alloc)
    {
    }




    enum { E_LIMITS_INIT = 0 };
     enum { E_LIMITS_DISABLED = 1 };
     enum { E_LIMITS_ENABLED = 2 };
     enum { E_LIMITS_TRIGGERED = 3 };
     enum { E_LIMITS_RECOVERING = 4 };
     enum { E_LIMITS_RECOVERED = 5 };
 

  typedef boost::shared_ptr< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct E_LIMITS_STATE_

typedef ::mavlink_udp::E_LIMITS_STATE_<std::allocator<void> > E_LIMITS_STATE;

typedef boost::shared_ptr< ::mavlink_udp::E_LIMITS_STATE > E_LIMITS_STATEPtr;
typedef boost::shared_ptr< ::mavlink_udp::E_LIMITS_STATE const> E_LIMITS_STATEConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_udp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mavlink_udp': ['/root/ehang_ws/src/ghost/mavlink_udp/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1822eb999765e04390d2e92c76b0213";
  }

  static const char* value(const ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1822eb999765e04ULL;
  static const uint64_t static_value2 = 0x390d2e92c76b0213ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_udp/E_LIMITS_STATE";
  }

  static const char* value(const ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in <function get_timestamp at 0x2710500>\n\
# ENUM: E_LIMITS_STATE\n\
#  pre-initialization\n\
uint8 E_LIMITS_INIT = 0\n\
#  disabled\n\
uint8 E_LIMITS_DISABLED = 1\n\
#  checking limits\n\
uint8 E_LIMITS_ENABLED = 2\n\
#  a limit has been breached\n\
uint8 E_LIMITS_TRIGGERED = 3\n\
#  taking action eg. RTL\n\
uint8 E_LIMITS_RECOVERING = 4\n\
#  we're no longer in breach of a limit\n\
uint8 E_LIMITS_RECOVERED = 5\n\
";
  }

  static const char* value(const ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct E_LIMITS_STATE_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mavlink_udp::E_LIMITS_STATE_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_UDP_MESSAGE_E_LIMITS_STATE_H
