/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_udp/msg/MAV_RAW_DATA.msg
 *
 */


#ifndef MAVLINK_UDP_MESSAGE_MAV_RAW_DATA_H
#define MAVLINK_UDP_MESSAGE_MAV_RAW_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_udp
{
template <class ContainerAllocator>
struct MAV_RAW_DATA_
{
  typedef MAV_RAW_DATA_<ContainerAllocator> Type;

  MAV_RAW_DATA_()
    : channel(0)
    , data()  {
    }
  MAV_RAW_DATA_(const ContainerAllocator& _alloc)
    : channel(0)
    , data(_alloc)  {
    }



   typedef uint8_t _channel_type;
  _channel_type channel;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;


    enum { CH_COMM0 = 0 };
     enum { CH_COMM1 = 1 };
     enum { CH_COMM2 = 2 };
     enum { CH_COMM3 = 3 };
 

  typedef boost::shared_ptr< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MAV_RAW_DATA_

typedef ::mavlink_udp::MAV_RAW_DATA_<std::allocator<void> > MAV_RAW_DATA;

typedef boost::shared_ptr< ::mavlink_udp::MAV_RAW_DATA > MAV_RAW_DATAPtr;
typedef boost::shared_ptr< ::mavlink_udp::MAV_RAW_DATA const> MAV_RAW_DATAConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_udp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mavlink_udp': ['/root/ehang_ws/src/ghost/mavlink_udp/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe139ce95f69f25b7328e7afd6d8fcfe";
  }

  static const char* value(const ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe139ce95f69f25bULL;
  static const uint64_t static_value2 = 0x7328e7afd6d8fcfeULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_udp/MAV_RAW_DATA";
  }

  static const char* value(const ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint8 channel\n\
    uint8 CH_COMM0=0\n\
    uint8 CH_COMM1=1\n\
    uint8 CH_COMM2=2\n\
    uint8 CH_COMM3=3\n\
uint8[] data\n\
";
  }

  static const char* value(const ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MAV_RAW_DATA_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_udp::MAV_RAW_DATA_<ContainerAllocator>& v)
  {
    s << indent << "channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.channel);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_UDP_MESSAGE_MAV_RAW_DATA_H
