/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_udp/msg/MOUNT_CONFIGURE.msg
 *
 */


#ifndef MAVLINK_UDP_MESSAGE_MOUNT_CONFIGURE_H
#define MAVLINK_UDP_MESSAGE_MOUNT_CONFIGURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_udp
{
template <class ContainerAllocator>
struct MOUNT_CONFIGURE_
{
  typedef MOUNT_CONFIGURE_<ContainerAllocator> Type;

  MOUNT_CONFIGURE_()
    : sysid(0)
    , compid(0)
    , target_system(0)
    , target_component(0)
    , mount_mode(0)
    , stab_roll(0)
    , stab_pitch(0)
    , stab_yaw(0)  {
    }
  MOUNT_CONFIGURE_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , target_system(0)
    , target_component(0)
    , mount_mode(0)
    , stab_roll(0)
    , stab_pitch(0)
    , stab_yaw(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _target_system_type;
  _target_system_type target_system;

   typedef uint8_t _target_component_type;
  _target_component_type target_component;

   typedef uint8_t _mount_mode_type;
  _mount_mode_type mount_mode;

   typedef uint8_t _stab_roll_type;
  _stab_roll_type stab_roll;

   typedef uint8_t _stab_pitch_type;
  _stab_pitch_type stab_pitch;

   typedef uint8_t _stab_yaw_type;
  _stab_yaw_type stab_yaw;


    enum { ID = 156 };
 

  typedef boost::shared_ptr< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MOUNT_CONFIGURE_

typedef ::mavlink_udp::MOUNT_CONFIGURE_<std::allocator<void> > MOUNT_CONFIGURE;

typedef boost::shared_ptr< ::mavlink_udp::MOUNT_CONFIGURE > MOUNT_CONFIGUREPtr;
typedef boost::shared_ptr< ::mavlink_udp::MOUNT_CONFIGURE const> MOUNT_CONFIGUREConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_udp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mavlink_udp': ['/root/ehang_ws/src/ghost/mavlink_udp/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06b27e44881fb6ea69d679e913d80ed6";
  }

  static const char* value(const ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06b27e44881fb6eaULL;
  static const uint64_t static_value2 = 0x69d679e913d80ed6ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_udp/MOUNT_CONFIGURE";
  }

  static const char* value(const ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.913526\n\
# MESSAGE: MOUNT_CONFIGURE\n\
# Description:Message to configure a camera mount, directional antenna, etc.\n\
uint8 ID = 156\n\
uint8 sysid\n\
uint8 compid\n\
uint8 target_system\n\
uint8 target_component\n\
uint8 mount_mode\n\
uint8 stab_roll\n\
uint8 stab_pitch\n\
uint8 stab_yaw\n\
";
  }

  static const char* value(const ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.target_system);
      stream.next(m.target_component);
      stream.next(m.mount_mode);
      stream.next(m.stab_roll);
      stream.next(m.stab_pitch);
      stream.next(m.stab_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MOUNT_CONFIGURE_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_udp::MOUNT_CONFIGURE_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "target_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_system);
    s << indent << "target_component: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_component);
    s << indent << "mount_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mount_mode);
    s << indent << "stab_roll: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stab_roll);
    s << indent << "stab_pitch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stab_pitch);
    s << indent << "stab_yaw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stab_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_UDP_MESSAGE_MOUNT_CONFIGURE_H
