/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_udp/msg/MOUNT_CONTROL.msg
 *
 */


#ifndef MAVLINK_UDP_MESSAGE_MOUNT_CONTROL_H
#define MAVLINK_UDP_MESSAGE_MOUNT_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_udp
{
template <class ContainerAllocator>
struct MOUNT_CONTROL_
{
  typedef MOUNT_CONTROL_<ContainerAllocator> Type;

  MOUNT_CONTROL_()
    : sysid(0)
    , compid(0)
    , target_system(0)
    , target_component(0)
    , input_a(0)
    , input_b(0)
    , input_c(0)
    , save_position(0)  {
    }
  MOUNT_CONTROL_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , target_system(0)
    , target_component(0)
    , input_a(0)
    , input_b(0)
    , input_c(0)
    , save_position(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _target_system_type;
  _target_system_type target_system;

   typedef uint8_t _target_component_type;
  _target_component_type target_component;

   typedef int32_t _input_a_type;
  _input_a_type input_a;

   typedef int32_t _input_b_type;
  _input_b_type input_b;

   typedef int32_t _input_c_type;
  _input_c_type input_c;

   typedef uint8_t _save_position_type;
  _save_position_type save_position;


    enum { ID = 157 };
 

  typedef boost::shared_ptr< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MOUNT_CONTROL_

typedef ::mavlink_udp::MOUNT_CONTROL_<std::allocator<void> > MOUNT_CONTROL;

typedef boost::shared_ptr< ::mavlink_udp::MOUNT_CONTROL > MOUNT_CONTROLPtr;
typedef boost::shared_ptr< ::mavlink_udp::MOUNT_CONTROL const> MOUNT_CONTROLConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_udp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mavlink_udp': ['/root/ehang_ws/src/ghost/mavlink_udp/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2988aae91d6faf6426c88de7b85a117e";
  }

  static const char* value(const ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2988aae91d6faf64ULL;
  static const uint64_t static_value2 = 0x26c88de7b85a117eULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_udp/MOUNT_CONTROL";
  }

  static const char* value(const ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.913584\n\
# MESSAGE: MOUNT_CONTROL\n\
# Description:Message to control a camera mount, directional antenna, etc.\n\
uint8 ID = 157\n\
uint8 sysid\n\
uint8 compid\n\
uint8 target_system\n\
uint8 target_component\n\
int32 input_a\n\
int32 input_b\n\
int32 input_c\n\
uint8 save_position\n\
";
  }

  static const char* value(const ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.target_system);
      stream.next(m.target_component);
      stream.next(m.input_a);
      stream.next(m.input_b);
      stream.next(m.input_c);
      stream.next(m.save_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MOUNT_CONTROL_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_udp::MOUNT_CONTROL_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "target_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_system);
    s << indent << "target_component: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_component);
    s << indent << "input_a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input_a);
    s << indent << "input_b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input_b);
    s << indent << "input_c: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input_c);
    s << indent << "save_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.save_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_UDP_MESSAGE_MOUNT_CONTROL_H
