"""autogenerated by genpy from mavlink_ardupilotmega/MOUNT_CONTROL.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MOUNT_CONTROL(genpy.Message):
  _md5sum = "2988aae91d6faf6426c88de7b85a117e"
  _type = "mavlink_ardupilotmega/MOUNT_CONTROL"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Automatically Generated in 2014-08-12 13:24:39.913584
# MESSAGE: MOUNT_CONTROL
# Description:Message to control a camera mount, directional antenna, etc.
uint8 ID = 157
uint8 sysid
uint8 compid
uint8 target_system
uint8 target_component
int32 input_a
int32 input_b
int32 input_c
uint8 save_position

"""
  # Pseudo-constants
  ID = 157

  __slots__ = ['sysid','compid','target_system','target_component','input_a','input_b','input_c','save_position']
  _slot_types = ['uint8','uint8','uint8','uint8','int32','int32','int32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sysid,compid,target_system,target_component,input_a,input_b,input_c,save_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MOUNT_CONTROL, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sysid is None:
        self.sysid = 0
      if self.compid is None:
        self.compid = 0
      if self.target_system is None:
        self.target_system = 0
      if self.target_component is None:
        self.target_component = 0
      if self.input_a is None:
        self.input_a = 0
      if self.input_b is None:
        self.input_b = 0
      if self.input_c is None:
        self.input_c = 0
      if self.save_position is None:
        self.save_position = 0
    else:
      self.sysid = 0
      self.compid = 0
      self.target_system = 0
      self.target_component = 0
      self.input_a = 0
      self.input_b = 0
      self.input_c = 0
      self.save_position = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4B3iB.pack(_x.sysid, _x.compid, _x.target_system, _x.target_component, _x.input_a, _x.input_b, _x.input_c, _x.save_position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.sysid, _x.compid, _x.target_system, _x.target_component, _x.input_a, _x.input_b, _x.input_c, _x.save_position,) = _struct_4B3iB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4B3iB.pack(_x.sysid, _x.compid, _x.target_system, _x.target_component, _x.input_a, _x.input_b, _x.input_c, _x.save_position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.sysid, _x.compid, _x.target_system, _x.target_component, _x.input_a, _x.input_b, _x.input_c, _x.save_position,) = _struct_4B3iB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4B3iB = struct.Struct("<4B3iB")
