"""autogenerated by genpy from mavlink_common/GPS_STATUS.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GPS_STATUS(genpy.Message):
  _md5sum = "d6c5ba137f034801a81e81f9f0c19c16"
  _type = "mavlink_common/GPS_STATUS"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Automatically Generated in 2014-08-12 13:24:39.906861
# MESSAGE: GPS_STATUS
# Description:The positioning status, as reported by GPS. This message is intended to display status information about each satellite visible to the receiver. See message GLOBAL_POSITION for the global position estimate. This message can contain information for up to 20 satellites.
uint8 ID = 25
uint8 sysid
uint8 compid
uint8 satellites_visible
uint8[20] satellite_prn
uint8[20] satellite_used
uint8[20] satellite_elevation
uint8[20] satellite_azimuth
uint8[20] satellite_snr

"""
  # Pseudo-constants
  ID = 25

  __slots__ = ['sysid','compid','satellites_visible','satellite_prn','satellite_used','satellite_elevation','satellite_azimuth','satellite_snr']
  _slot_types = ['uint8','uint8','uint8','uint8[20]','uint8[20]','uint8[20]','uint8[20]','uint8[20]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sysid,compid,satellites_visible,satellite_prn,satellite_used,satellite_elevation,satellite_azimuth,satellite_snr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GPS_STATUS, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sysid is None:
        self.sysid = 0
      if self.compid is None:
        self.compid = 0
      if self.satellites_visible is None:
        self.satellites_visible = 0
      if self.satellite_prn is None:
        self.satellite_prn = chr(0)*20
      if self.satellite_used is None:
        self.satellite_used = chr(0)*20
      if self.satellite_elevation is None:
        self.satellite_elevation = chr(0)*20
      if self.satellite_azimuth is None:
        self.satellite_azimuth = chr(0)*20
      if self.satellite_snr is None:
        self.satellite_snr = chr(0)*20
    else:
      self.sysid = 0
      self.compid = 0
      self.satellites_visible = 0
      self.satellite_prn = chr(0)*20
      self.satellite_used = chr(0)*20
      self.satellite_elevation = chr(0)*20
      self.satellite_azimuth = chr(0)*20
      self.satellite_snr = chr(0)*20

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.sysid, _x.compid, _x.satellites_visible))
      _x = self.satellite_prn
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
      _x = self.satellite_used
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
      _x = self.satellite_elevation
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
      _x = self.satellite_azimuth
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
      _x = self.satellite_snr
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.sysid, _x.compid, _x.satellites_visible,) = _struct_3B.unpack(str[start:end])
      start = end
      end += 20
      self.satellite_prn = str[start:end]
      start = end
      end += 20
      self.satellite_used = str[start:end]
      start = end
      end += 20
      self.satellite_elevation = str[start:end]
      start = end
      end += 20
      self.satellite_azimuth = str[start:end]
      start = end
      end += 20
      self.satellite_snr = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.sysid, _x.compid, _x.satellites_visible))
      _x = self.satellite_prn
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
      _x = self.satellite_used
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
      _x = self.satellite_elevation
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
      _x = self.satellite_azimuth
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
      _x = self.satellite_snr
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_20B.pack(*_x))
      else:
        buff.write(_struct_20s.pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.sysid, _x.compid, _x.satellites_visible,) = _struct_3B.unpack(str[start:end])
      start = end
      end += 20
      self.satellite_prn = str[start:end]
      start = end
      end += 20
      self.satellite_used = str[start:end]
      start = end
      end += 20
      self.satellite_elevation = str[start:end]
      start = end
      end += 20
      self.satellite_azimuth = str[start:end]
      start = end
      end += 20
      self.satellite_snr = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B = struct.Struct("<3B")
_struct_20s = struct.Struct("<20s")
_struct_20B = struct.Struct("<20B")
