"""autogenerated by genpy from mavlink_common/RAW_PRESSURE.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RAW_PRESSURE(genpy.Message):
  _md5sum = "4f760573d883f477390cefc0df85f05a"
  _type = "mavlink_common/RAW_PRESSURE"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Automatically Generated in 2014-08-12 13:24:39.907120
# MESSAGE: RAW_PRESSURE
# Description:The RAW pressure readings for the typical setup of one absolute pressure and one differential pressure sensor. The sensor values should be the raw, UNSCALED ADC values.
uint8 ID = 28
uint8 sysid
uint8 compid
uint64 time_usec
int16 press_abs
int16 press_diff1
int16 press_diff2
int16 temperature

"""
  # Pseudo-constants
  ID = 28

  __slots__ = ['sysid','compid','time_usec','press_abs','press_diff1','press_diff2','temperature']
  _slot_types = ['uint8','uint8','uint64','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sysid,compid,time_usec,press_abs,press_diff1,press_diff2,temperature

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RAW_PRESSURE, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sysid is None:
        self.sysid = 0
      if self.compid is None:
        self.compid = 0
      if self.time_usec is None:
        self.time_usec = 0
      if self.press_abs is None:
        self.press_abs = 0
      if self.press_diff1 is None:
        self.press_diff1 = 0
      if self.press_diff2 is None:
        self.press_diff2 = 0
      if self.temperature is None:
        self.temperature = 0
    else:
      self.sysid = 0
      self.compid = 0
      self.time_usec = 0
      self.press_abs = 0
      self.press_diff1 = 0
      self.press_diff2 = 0
      self.temperature = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2BQ4h.pack(_x.sysid, _x.compid, _x.time_usec, _x.press_abs, _x.press_diff1, _x.press_diff2, _x.temperature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.sysid, _x.compid, _x.time_usec, _x.press_abs, _x.press_diff1, _x.press_diff2, _x.temperature,) = _struct_2BQ4h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2BQ4h.pack(_x.sysid, _x.compid, _x.time_usec, _x.press_abs, _x.press_diff1, _x.press_diff2, _x.temperature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.sysid, _x.compid, _x.time_usec, _x.press_abs, _x.press_diff1, _x.press_diff2, _x.temperature,) = _struct_2BQ4h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2BQ4h = struct.Struct("<2BQ4h")
