"""autogenerated by genpy from mavlink_common/SCALED_PRESSURE.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SCALED_PRESSURE(genpy.Message):
  _md5sum = "71c81def9a74f9d20ca8ebeed055bdfa"
  _type = "mavlink_common/SCALED_PRESSURE"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Automatically Generated in 2014-08-12 13:24:39.907209
# MESSAGE: SCALED_PRESSURE
# Description:The pressure readings for the typical setup of one absolute and differential pressure sensor. The units are as specified in each field.
uint8 ID = 29
uint8 sysid
uint8 compid
uint32 time_boot_ms
float32 press_abs
float32 press_diff
int16 temperature

"""
  # Pseudo-constants
  ID = 29

  __slots__ = ['sysid','compid','time_boot_ms','press_abs','press_diff','temperature']
  _slot_types = ['uint8','uint8','uint32','float32','float32','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sysid,compid,time_boot_ms,press_abs,press_diff,temperature

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SCALED_PRESSURE, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sysid is None:
        self.sysid = 0
      if self.compid is None:
        self.compid = 0
      if self.time_boot_ms is None:
        self.time_boot_ms = 0
      if self.press_abs is None:
        self.press_abs = 0.
      if self.press_diff is None:
        self.press_diff = 0.
      if self.temperature is None:
        self.temperature = 0
    else:
      self.sysid = 0
      self.compid = 0
      self.time_boot_ms = 0
      self.press_abs = 0.
      self.press_diff = 0.
      self.temperature = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2BI2fh.pack(_x.sysid, _x.compid, _x.time_boot_ms, _x.press_abs, _x.press_diff, _x.temperature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.sysid, _x.compid, _x.time_boot_ms, _x.press_abs, _x.press_diff, _x.temperature,) = _struct_2BI2fh.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2BI2fh.pack(_x.sysid, _x.compid, _x.time_boot_ms, _x.press_abs, _x.press_diff, _x.temperature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.sysid, _x.compid, _x.time_boot_ms, _x.press_abs, _x.press_diff, _x.temperature,) = _struct_2BI2fh.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2BI2fh = struct.Struct("<2BI2fh")
