"""autogenerated by genpy from mavlink_common/SCALED_IMU.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SCALED_IMU(genpy.Message):
  _md5sum = "7546ae484eed9b508c4e69262559baa4"
  _type = "mavlink_common/SCALED_IMU"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Automatically Generated in 2014-08-12 13:24:39.906926
# MESSAGE: SCALED_IMU
# Description:The RAW IMU readings for the usual 9DOF sensor setup. This message should contain the scaled values to the described units
uint8 ID = 26
uint8 sysid
uint8 compid
uint32 time_boot_ms
int16 xacc
int16 yacc
int16 zacc
int16 xgyro
int16 ygyro
int16 zgyro
int16 xmag
int16 ymag
int16 zmag

"""
  # Pseudo-constants
  ID = 26

  __slots__ = ['sysid','compid','time_boot_ms','xacc','yacc','zacc','xgyro','ygyro','zgyro','xmag','ymag','zmag']
  _slot_types = ['uint8','uint8','uint32','int16','int16','int16','int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sysid,compid,time_boot_ms,xacc,yacc,zacc,xgyro,ygyro,zgyro,xmag,ymag,zmag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SCALED_IMU, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sysid is None:
        self.sysid = 0
      if self.compid is None:
        self.compid = 0
      if self.time_boot_ms is None:
        self.time_boot_ms = 0
      if self.xacc is None:
        self.xacc = 0
      if self.yacc is None:
        self.yacc = 0
      if self.zacc is None:
        self.zacc = 0
      if self.xgyro is None:
        self.xgyro = 0
      if self.ygyro is None:
        self.ygyro = 0
      if self.zgyro is None:
        self.zgyro = 0
      if self.xmag is None:
        self.xmag = 0
      if self.ymag is None:
        self.ymag = 0
      if self.zmag is None:
        self.zmag = 0
    else:
      self.sysid = 0
      self.compid = 0
      self.time_boot_ms = 0
      self.xacc = 0
      self.yacc = 0
      self.zacc = 0
      self.xgyro = 0
      self.ygyro = 0
      self.zgyro = 0
      self.xmag = 0
      self.ymag = 0
      self.zmag = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2BI9h.pack(_x.sysid, _x.compid, _x.time_boot_ms, _x.xacc, _x.yacc, _x.zacc, _x.xgyro, _x.ygyro, _x.zgyro, _x.xmag, _x.ymag, _x.zmag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.sysid, _x.compid, _x.time_boot_ms, _x.xacc, _x.yacc, _x.zacc, _x.xgyro, _x.ygyro, _x.zgyro, _x.xmag, _x.ymag, _x.zmag,) = _struct_2BI9h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2BI9h.pack(_x.sysid, _x.compid, _x.time_boot_ms, _x.xacc, _x.yacc, _x.zacc, _x.xgyro, _x.ygyro, _x.zgyro, _x.xmag, _x.ymag, _x.zmag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.sysid, _x.compid, _x.time_boot_ms, _x.xacc, _x.yacc, _x.zacc, _x.xgyro, _x.ygyro, _x.zgyro, _x.xmag, _x.ymag, _x.zmag,) = _struct_2BI9h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2BI9h = struct.Struct("<2BI9h")
