/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_ardupilotmega/msg/RADIO.msg
 *
 */


#ifndef MAVLINK_ARDUPILOTMEGA_MESSAGE_RADIO_H
#define MAVLINK_ARDUPILOTMEGA_MESSAGE_RADIO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_ardupilotmega
{
template <class ContainerAllocator>
struct RADIO_
{
  typedef RADIO_<ContainerAllocator> Type;

  RADIO_()
    : sysid(0)
    , compid(0)
    , rssi(0)
    , remrssi(0)
    , txbuf(0)
    , noise(0)
    , remnoise(0)
    , rxerrors(0)
    , fixed(0)  {
    }
  RADIO_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , rssi(0)
    , remrssi(0)
    , txbuf(0)
    , noise(0)
    , remnoise(0)
    , rxerrors(0)
    , fixed(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _rssi_type;
  _rssi_type rssi;

   typedef uint8_t _remrssi_type;
  _remrssi_type remrssi;

   typedef uint8_t _txbuf_type;
  _txbuf_type txbuf;

   typedef uint8_t _noise_type;
  _noise_type noise;

   typedef uint8_t _remnoise_type;
  _remnoise_type remnoise;

   typedef uint16_t _rxerrors_type;
  _rxerrors_type rxerrors;

   typedef uint16_t _fixed_type;
  _fixed_type fixed;


    enum { ID = 166 };
 

  typedef boost::shared_ptr< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct RADIO_

typedef ::mavlink_ardupilotmega::RADIO_<std::allocator<void> > RADIO;

typedef boost::shared_ptr< ::mavlink_ardupilotmega::RADIO > RADIOPtr;
typedef boost::shared_ptr< ::mavlink_ardupilotmega::RADIO const> RADIOConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_ardupilotmega

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_ardupilotmega': ['/root/ehang_ws/src/ghost/mavlink_ardupilotmega/msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74a7c3868a599c60cefb72b3c236fd99";
  }

  static const char* value(const ::mavlink_ardupilotmega::RADIO_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74a7c3868a599c60ULL;
  static const uint64_t static_value2 = 0xcefb72b3c236fd99ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_ardupilotmega/RADIO";
  }

  static const char* value(const ::mavlink_ardupilotmega::RADIO_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.914042\n\
# MESSAGE: RADIO\n\
# Description:Status generated by radio\n\
uint8 ID = 166\n\
uint8 sysid\n\
uint8 compid\n\
uint8 rssi\n\
uint8 remrssi\n\
uint8 txbuf\n\
uint8 noise\n\
uint8 remnoise\n\
uint16 rxerrors\n\
uint16 fixed\n\
";
  }

  static const char* value(const ::mavlink_ardupilotmega::RADIO_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.rssi);
      stream.next(m.remrssi);
      stream.next(m.txbuf);
      stream.next(m.noise);
      stream.next(m.remnoise);
      stream.next(m.rxerrors);
      stream.next(m.fixed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RADIO_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_ardupilotmega::RADIO_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_ardupilotmega::RADIO_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "rssi: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rssi);
    s << indent << "remrssi: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remrssi);
    s << indent << "txbuf: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.txbuf);
    s << indent << "noise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.noise);
    s << indent << "remnoise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remnoise);
    s << indent << "rxerrors: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rxerrors);
    s << indent << "fixed: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.fixed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_ARDUPILOTMEGA_MESSAGE_RADIO_H
