(cl:in-package mavlink_ardupilotmega-msg)
(cl:export '(SYSID-VAL
          SYSID
          COMPID-VAL
          COMPID
          MAG_OFS_X-VAL
          MAG_OFS_X
          MAG_OFS_Y-VAL
          MAG_OFS_Y
          MAG_OFS_Z-VAL
          MAG_OFS_Z
          MAG_DECLINATION-VAL
          MAG_DECLINATION
          RAW_PRESS-VAL
          RAW_PRESS
          RAW_TEMP-VAL
          RAW_TEMP
          GYRO_CAL_X-VAL
          GYRO_CAL_X
          GYRO_CAL_Y-VAL
          GYRO_CAL_Y
          GYRO_CAL_Z-VAL
          GYRO_CAL_Z
          ACCEL_CAL_X-VAL
          ACCEL_CAL_X
          ACCEL_CAL_Y-VAL
          ACCEL_CAL_Y
          ACCEL_CAL_Z-VAL
          ACCEL_CAL_Z
))