(cl:in-package mavlink_common-msg)
(cl:export '(SYSID-VAL
          SYSID
          COMPID-VAL
          COMPID
          TARGET_SYSTEM-VAL
          TARGET_SYSTEM
          TARGET_COMPONENT-VAL
          TARGET_COMPONENT
          SEQ-VAL
          SEQ
          FRAME-VAL
          FRAME
          COMMAND-VAL
          COMMAND
          CURRENT-VAL
          CURRENT
          AUTOCONTINUE-VAL
          AUTOCONTINUE
          PARAM1-VAL
          PARAM1
          PARAM2-VAL
          PARAM2
          PARAM3-VAL
          PARAM3
          PARAM4-VAL
          PARAM4
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
))