(cl:in-package mavlink_common-msg)
(cl:export '(SYSID-VAL
          SYSID
          COMPID-VAL
          COMPID
          TIME_USEC-VAL
          TIME_USEC
          CHAN1_RAW-VAL
          CHAN1_RAW
          CHAN2_RAW-VAL
          CHAN2_RAW
          CHAN3_RAW-VAL
          CHAN3_RAW
          CHAN4_RAW-VAL
          CHAN4_RAW
          CHAN5_RAW-VAL
          CHAN5_RAW
          CHAN6_RAW-VAL
          CHAN6_RAW
          CHAN7_RAW-VAL
          CHAN7_RAW
          CHAN8_RAW-VAL
          CHAN8_RAW
          CHAN9_RAW-VAL
          CHAN9_RAW
          CHAN10_RAW-VAL
          CHAN10_RAW
          CHAN11_RAW-VAL
          CHAN11_RAW
          CHAN12_RAW-VAL
          CHAN12_RAW
          RSSI-VAL
          RSSI
))