(cl:in-package mavlink_common-msg)
(cl:export '(SYSID-VAL
          SYSID
          COMPID-VAL
          COMPID
          TIME_USEC-VAL
          TIME_USEC
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ROLLSPEED-VAL
          ROLLSPEED
          PITCHSPEED-VAL
          PITCHSPEED
          YAWSPEED-VAL
          YAWSPEED
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          XACC-VAL
          XACC
          YACC-VAL
          YACC
          ZACC-VAL
          ZACC
))