/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/ATTITUDE_QUATERNION.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_ATTITUDE_QUATERNION_H
#define MAVLINK_COMMON_MESSAGE_ATTITUDE_QUATERNION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct ATTITUDE_QUATERNION_
{
  typedef ATTITUDE_QUATERNION_<ContainerAllocator> Type;

  ATTITUDE_QUATERNION_()
    : sysid(0)
    , compid(0)
    , time_boot_ms(0)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)
    , q4(0.0)
    , rollspeed(0.0)
    , pitchspeed(0.0)
    , yawspeed(0.0)  {
    }
  ATTITUDE_QUATERNION_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , time_boot_ms(0)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)
    , q4(0.0)
    , rollspeed(0.0)
    , pitchspeed(0.0)
    , yawspeed(0.0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint32_t _time_boot_ms_type;
  _time_boot_ms_type time_boot_ms;

   typedef float _q1_type;
  _q1_type q1;

   typedef float _q2_type;
  _q2_type q2;

   typedef float _q3_type;
  _q3_type q3;

   typedef float _q4_type;
  _q4_type q4;

   typedef float _rollspeed_type;
  _rollspeed_type rollspeed;

   typedef float _pitchspeed_type;
  _pitchspeed_type pitchspeed;

   typedef float _yawspeed_type;
  _yawspeed_type yawspeed;


    enum { ID = 31 };
 

  typedef boost::shared_ptr< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ATTITUDE_QUATERNION_

typedef ::mavlink_common::ATTITUDE_QUATERNION_<std::allocator<void> > ATTITUDE_QUATERNION;

typedef boost::shared_ptr< ::mavlink_common::ATTITUDE_QUATERNION > ATTITUDE_QUATERNIONPtr;
typedef boost::shared_ptr< ::mavlink_common::ATTITUDE_QUATERNION const> ATTITUDE_QUATERNIONConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88963a9c2789496248bcd10004c27d0b";
  }

  static const char* value(const ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88963a9c27894962ULL;
  static const uint64_t static_value2 = 0x48bcd10004c27d0bULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/ATTITUDE_QUATERNION";
  }

  static const char* value(const ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.907357\n\
# MESSAGE: ATTITUDE_QUATERNION\n\
# Description:The attitude in the aeronautical frame (right-handed, Z-down, X-front, Y-right), expressed as quaternion.\n\
uint8 ID = 31\n\
uint8 sysid\n\
uint8 compid\n\
uint32 time_boot_ms\n\
float32 q1\n\
float32 q2\n\
float32 q3\n\
float32 q4\n\
float32 rollspeed\n\
float32 pitchspeed\n\
float32 yawspeed\n\
";
  }

  static const char* value(const ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.time_boot_ms);
      stream.next(m.q1);
      stream.next(m.q2);
      stream.next(m.q3);
      stream.next(m.q4);
      stream.next(m.rollspeed);
      stream.next(m.pitchspeed);
      stream.next(m.yawspeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ATTITUDE_QUATERNION_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::ATTITUDE_QUATERNION_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "time_boot_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_boot_ms);
    s << indent << "q1: ";
    Printer<float>::stream(s, indent + "  ", v.q1);
    s << indent << "q2: ";
    Printer<float>::stream(s, indent + "  ", v.q2);
    s << indent << "q3: ";
    Printer<float>::stream(s, indent + "  ", v.q3);
    s << indent << "q4: ";
    Printer<float>::stream(s, indent + "  ", v.q4);
    s << indent << "rollspeed: ";
    Printer<float>::stream(s, indent + "  ", v.rollspeed);
    s << indent << "pitchspeed: ";
    Printer<float>::stream(s, indent + "  ", v.pitchspeed);
    s << indent << "yawspeed: ";
    Printer<float>::stream(s, indent + "  ", v.yawspeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_ATTITUDE_QUATERNION_H
