/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/AUTH_KEY.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_AUTH_KEY_H
#define MAVLINK_COMMON_MESSAGE_AUTH_KEY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct AUTH_KEY_
{
  typedef AUTH_KEY_<ContainerAllocator> Type;

  AUTH_KEY_()
    : sysid(0)
    , compid(0)
    , key()  {
      key.assign(0);
  }
  AUTH_KEY_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , key()  {
      key.assign(0);
  }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef boost::array<uint8_t, 32>  _key_type;
  _key_type key;


    enum { ID = 7 };
 

  typedef boost::shared_ptr< ::mavlink_common::AUTH_KEY_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::AUTH_KEY_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct AUTH_KEY_

typedef ::mavlink_common::AUTH_KEY_<std::allocator<void> > AUTH_KEY;

typedef boost::shared_ptr< ::mavlink_common::AUTH_KEY > AUTH_KEYPtr;
typedef boost::shared_ptr< ::mavlink_common::AUTH_KEY const> AUTH_KEYConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::AUTH_KEY_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::AUTH_KEY_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::AUTH_KEY_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::AUTH_KEY_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e54907323a6b7953ac83c54ab525f282";
  }

  static const char* value(const ::mavlink_common::AUTH_KEY_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe54907323a6b7953ULL;
  static const uint64_t static_value2 = 0xac83c54ab525f282ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/AUTH_KEY";
  }

  static const char* value(const ::mavlink_common::AUTH_KEY_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.906353\n\
# MESSAGE: AUTH_KEY\n\
# Description:Emit an encrypted signature / key identifying this system. PLEASE NOTE: This protocol has been kept simple, so transmitting the key requires an encrypted channel for true safety.\n\
uint8 ID = 7\n\
uint8 sysid\n\
uint8 compid\n\
char[32] key\n\
";
  }

  static const char* value(const ::mavlink_common::AUTH_KEY_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AUTH_KEY_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::AUTH_KEY_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::AUTH_KEY_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "key[]" << std::endl;
    for (size_t i = 0; i < v.key.size(); ++i)
    {
      s << indent << "  key[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.key[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_AUTH_KEY_H
