/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/BATTERY_STATUS.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_BATTERY_STATUS_H
#define MAVLINK_COMMON_MESSAGE_BATTERY_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct BATTERY_STATUS_
{
  typedef BATTERY_STATUS_<ContainerAllocator> Type;

  BATTERY_STATUS_()
    : sysid(0)
    , compid(0)
    , accu_id(0)
    , voltage_cell_1(0)
    , voltage_cell_2(0)
    , voltage_cell_3(0)
    , voltage_cell_4(0)
    , voltage_cell_5(0)
    , voltage_cell_6(0)
    , current_battery(0)
    , battery_remaining(0)  {
    }
  BATTERY_STATUS_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , accu_id(0)
    , voltage_cell_1(0)
    , voltage_cell_2(0)
    , voltage_cell_3(0)
    , voltage_cell_4(0)
    , voltage_cell_5(0)
    , voltage_cell_6(0)
    , current_battery(0)
    , battery_remaining(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _accu_id_type;
  _accu_id_type accu_id;

   typedef uint16_t _voltage_cell_1_type;
  _voltage_cell_1_type voltage_cell_1;

   typedef uint16_t _voltage_cell_2_type;
  _voltage_cell_2_type voltage_cell_2;

   typedef uint16_t _voltage_cell_3_type;
  _voltage_cell_3_type voltage_cell_3;

   typedef uint16_t _voltage_cell_4_type;
  _voltage_cell_4_type voltage_cell_4;

   typedef uint16_t _voltage_cell_5_type;
  _voltage_cell_5_type voltage_cell_5;

   typedef uint16_t _voltage_cell_6_type;
  _voltage_cell_6_type voltage_cell_6;

   typedef int16_t _current_battery_type;
  _current_battery_type current_battery;

   typedef int8_t _battery_remaining_type;
  _battery_remaining_type battery_remaining;


    enum { ID = 147 };
 

  typedef boost::shared_ptr< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct BATTERY_STATUS_

typedef ::mavlink_common::BATTERY_STATUS_<std::allocator<void> > BATTERY_STATUS;

typedef boost::shared_ptr< ::mavlink_common::BATTERY_STATUS > BATTERY_STATUSPtr;
typedef boost::shared_ptr< ::mavlink_common::BATTERY_STATUS const> BATTERY_STATUSConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46796da16460f852425771f02c16daac";
  }

  static const char* value(const ::mavlink_common::BATTERY_STATUS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46796da16460f852ULL;
  static const uint64_t static_value2 = 0x425771f02c16daacULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/BATTERY_STATUS";
  }

  static const char* value(const ::mavlink_common::BATTERY_STATUS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.910704\n\
# MESSAGE: BATTERY_STATUS\n\
# Description:Transmitte battery informations for a accu pack.\n\
uint8 ID = 147\n\
uint8 sysid\n\
uint8 compid\n\
uint8 accu_id\n\
uint16 voltage_cell_1\n\
uint16 voltage_cell_2\n\
uint16 voltage_cell_3\n\
uint16 voltage_cell_4\n\
uint16 voltage_cell_5\n\
uint16 voltage_cell_6\n\
int16 current_battery\n\
int8 battery_remaining\n\
";
  }

  static const char* value(const ::mavlink_common::BATTERY_STATUS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.accu_id);
      stream.next(m.voltage_cell_1);
      stream.next(m.voltage_cell_2);
      stream.next(m.voltage_cell_3);
      stream.next(m.voltage_cell_4);
      stream.next(m.voltage_cell_5);
      stream.next(m.voltage_cell_6);
      stream.next(m.current_battery);
      stream.next(m.battery_remaining);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BATTERY_STATUS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::BATTERY_STATUS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::BATTERY_STATUS_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "accu_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accu_id);
    s << indent << "voltage_cell_1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.voltage_cell_1);
    s << indent << "voltage_cell_2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.voltage_cell_2);
    s << indent << "voltage_cell_3: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.voltage_cell_3);
    s << indent << "voltage_cell_4: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.voltage_cell_4);
    s << indent << "voltage_cell_5: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.voltage_cell_5);
    s << indent << "voltage_cell_6: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.voltage_cell_6);
    s << indent << "current_battery: ";
    Printer<int16_t>::stream(s, indent + "  ", v.current_battery);
    s << indent << "battery_remaining: ";
    Printer<int8_t>::stream(s, indent + "  ", v.battery_remaining);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_BATTERY_STATUS_H
