/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/E_MAV_AUTOPILOT.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_E_MAV_AUTOPILOT_H
#define MAVLINK_COMMON_MESSAGE_E_MAV_AUTOPILOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct E_MAV_AUTOPILOT_
{
  typedef E_MAV_AUTOPILOT_<ContainerAllocator> Type;

  E_MAV_AUTOPILOT_()
    {
    }
  E_MAV_AUTOPILOT_(const ContainerAllocator& _alloc)
    {
    }




    enum { E_MAV_AUTOPILOT_GENERIC = 0 };
     enum { E_MAV_AUTOPILOT_PIXHAWK = 1 };
     enum { E_MAV_AUTOPILOT_SLUGS = 2 };
     enum { E_MAV_AUTOPILOT_ARDUPILOTMEGA = 3 };
     enum { E_MAV_AUTOPILOT_OPENPILOT = 4 };
     enum { E_MAV_AUTOPILOT_GENERIC_WAYPOINTS_ONLY = 5 };
     enum { E_MAV_AUTOPILOT_GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY = 6 };
     enum { E_MAV_AUTOPILOT_GENERIC_MISSION_FULL = 7 };
     enum { E_MAV_AUTOPILOT_INVALID = 8 };
     enum { E_MAV_AUTOPILOT_PPZ = 9 };
     enum { E_MAV_AUTOPILOT_UDB = 10 };
     enum { E_MAV_AUTOPILOT_FP = 11 };
     enum { E_MAV_AUTOPILOT_PX4 = 12 };
 

  typedef boost::shared_ptr< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct E_MAV_AUTOPILOT_

typedef ::mavlink_common::E_MAV_AUTOPILOT_<std::allocator<void> > E_MAV_AUTOPILOT;

typedef boost::shared_ptr< ::mavlink_common::E_MAV_AUTOPILOT > E_MAV_AUTOPILOTPtr;
typedef boost::shared_ptr< ::mavlink_common::E_MAV_AUTOPILOT const> E_MAV_AUTOPILOTConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47031416e2eeabfb176ee8ac407f1239";
  }

  static const char* value(const ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47031416e2eeabfbULL;
  static const uint64_t static_value2 = 0x176ee8ac407f1239ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/E_MAV_AUTOPILOT";
  }

  static const char* value(const ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in <function get_timestamp at 0x2710500>\n\
# ENUM: E_MAV_AUTOPILOT\n\
# Description:Micro air vehicle / autopilot classes. This identifies the individual model.\n\
# Generic autopilot, full support for everything\n\
uint8 E_MAV_AUTOPILOT_GENERIC = 0\n\
# PIXHAWK autopilot, http://pixhawk.ethz.ch\n\
uint8 E_MAV_AUTOPILOT_PIXHAWK = 1\n\
# SLUGS autopilot, http://slugsuav.soe.ucsc.edu\n\
uint8 E_MAV_AUTOPILOT_SLUGS = 2\n\
# ArduPilotMega / ArduCopter, http://diydrones.com\n\
uint8 E_MAV_AUTOPILOT_ARDUPILOTMEGA = 3\n\
# OpenPilot, http://openpilot.org\n\
uint8 E_MAV_AUTOPILOT_OPENPILOT = 4\n\
# Generic autopilot only supporting simple waypoints\n\
uint8 E_MAV_AUTOPILOT_GENERIC_WAYPOINTS_ONLY = 5\n\
# Generic autopilot supporting waypoints and other simple navigation commands\n\
uint8 E_MAV_AUTOPILOT_GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY = 6\n\
# Generic autopilot supporting the full mission command set\n\
uint8 E_MAV_AUTOPILOT_GENERIC_MISSION_FULL = 7\n\
# No valid autopilot, e.g. a GCS or other MAVLink component\n\
uint8 E_MAV_AUTOPILOT_INVALID = 8\n\
# PPZ UAV - http://nongnu.org/paparazzi\n\
uint8 E_MAV_AUTOPILOT_PPZ = 9\n\
# UAV Dev Board\n\
uint8 E_MAV_AUTOPILOT_UDB = 10\n\
# FlexiPilot\n\
uint8 E_MAV_AUTOPILOT_FP = 11\n\
# PX4 Autopilot - http://pixhawk.ethz.ch/px4/\n\
uint8 E_MAV_AUTOPILOT_PX4 = 12\n\
";
  }

  static const char* value(const ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct E_MAV_AUTOPILOT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mavlink_common::E_MAV_AUTOPILOT_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_E_MAV_AUTOPILOT_H
