/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/E_MAV_CMD_ACK.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_E_MAV_CMD_ACK_H
#define MAVLINK_COMMON_MESSAGE_E_MAV_CMD_ACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct E_MAV_CMD_ACK_
{
  typedef E_MAV_CMD_ACK_<ContainerAllocator> Type;

  E_MAV_CMD_ACK_()
    {
    }
  E_MAV_CMD_ACK_(const ContainerAllocator& _alloc)
    {
    }




    enum { E_MAV_CMD_ACK_OK = 1 };
     enum { E_MAV_CMD_ACK_ERR_FAIL = 2 };
     enum { E_MAV_CMD_ACK_ERR_ACCESS_DENIED = 3 };
     enum { E_MAV_CMD_ACK_ERR_NOT_SUPPORTED = 4 };
     enum { E_MAV_CMD_ACK_ERR_COORDINATE_FRAME_NOT_SUPPORTED = 5 };
     enum { E_MAV_CMD_ACK_ERR_COORDINATES_OUT_OF_RANGE = 6 };
     enum { E_MAV_CMD_ACK_ERR_X_LAT_OUT_OF_RANGE = 7 };
     enum { E_MAV_CMD_ACK_ERR_Y_LON_OUT_OF_RANGE = 8 };
     enum { E_MAV_CMD_ACK_ERR_Z_ALT_OUT_OF_RANGE = 9 };
 

  typedef boost::shared_ptr< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct E_MAV_CMD_ACK_

typedef ::mavlink_common::E_MAV_CMD_ACK_<std::allocator<void> > E_MAV_CMD_ACK;

typedef boost::shared_ptr< ::mavlink_common::E_MAV_CMD_ACK > E_MAV_CMD_ACKPtr;
typedef boost::shared_ptr< ::mavlink_common::E_MAV_CMD_ACK const> E_MAV_CMD_ACKConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b61741c359ed1a4150e49a0a9e52b9e0";
  }

  static const char* value(const ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb61741c359ed1a41ULL;
  static const uint64_t static_value2 = 0x50e49a0a9e52b9e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/E_MAV_CMD_ACK";
  }

  static const char* value(const ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in <function get_timestamp at 0x2710500>\n\
# ENUM: E_MAV_CMD_ACK\n\
# Description:ACK / NACK / ERROR values as a result of MAV_CMDs and for mission item transmission.\n\
# Command / mission item is ok.\n\
uint8 E_MAV_CMD_ACK_OK = 1\n\
# Generic error message if none of the other reasons fails or if no detailed error reporting is implemented.\n\
uint8 E_MAV_CMD_ACK_ERR_FAIL = 2\n\
# The system is refusing to accept this command from this source / communication partner.\n\
uint8 E_MAV_CMD_ACK_ERR_ACCESS_DENIED = 3\n\
# Command or mission item is not supported, other commands would be accepted.\n\
uint8 E_MAV_CMD_ACK_ERR_NOT_SUPPORTED = 4\n\
# The coordinate frame of this command / mission item is not supported.\n\
uint8 E_MAV_CMD_ACK_ERR_COORDINATE_FRAME_NOT_SUPPORTED = 5\n\
# The coordinate frame of this command is ok, but he coordinate values exceed the safety limits of this system. This is a generic error, please use the more specific error messages below if possible.\n\
uint8 E_MAV_CMD_ACK_ERR_COORDINATES_OUT_OF_RANGE = 6\n\
# The X or latitude value is out of range.\n\
uint8 E_MAV_CMD_ACK_ERR_X_LAT_OUT_OF_RANGE = 7\n\
# The Y or longitude value is out of range.\n\
uint8 E_MAV_CMD_ACK_ERR_Y_LON_OUT_OF_RANGE = 8\n\
# The Z or altitude value is out of range.\n\
uint8 E_MAV_CMD_ACK_ERR_Z_ALT_OUT_OF_RANGE = 9\n\
";
  }

  static const char* value(const ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct E_MAV_CMD_ACK_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mavlink_common::E_MAV_CMD_ACK_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_E_MAV_CMD_ACK_H
