/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/E_MAV_DATA_STREAM.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_E_MAV_DATA_STREAM_H
#define MAVLINK_COMMON_MESSAGE_E_MAV_DATA_STREAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct E_MAV_DATA_STREAM_
{
  typedef E_MAV_DATA_STREAM_<ContainerAllocator> Type;

  E_MAV_DATA_STREAM_()
    {
    }
  E_MAV_DATA_STREAM_(const ContainerAllocator& _alloc)
    {
    }




    enum { E_MAV_DATA_STREAM_ALL = 0 };
     enum { E_MAV_DATA_STREAM_RAW_SENSORS = 1 };
     enum { E_MAV_DATA_STREAM_EXTENDED_STATUS = 2 };
     enum { E_MAV_DATA_STREAM_RC_CHANNELS = 3 };
     enum { E_MAV_DATA_STREAM_RAW_CONTROLLER = 4 };
     enum { E_MAV_DATA_STREAM_POSITION = 6 };
     enum { E_MAV_DATA_STREAM_EXTRA1 = 10 };
     enum { E_MAV_DATA_STREAM_EXTRA2 = 11 };
     enum { E_MAV_DATA_STREAM_EXTRA3 = 12 };
 

  typedef boost::shared_ptr< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct E_MAV_DATA_STREAM_

typedef ::mavlink_common::E_MAV_DATA_STREAM_<std::allocator<void> > E_MAV_DATA_STREAM;

typedef boost::shared_ptr< ::mavlink_common::E_MAV_DATA_STREAM > E_MAV_DATA_STREAMPtr;
typedef boost::shared_ptr< ::mavlink_common::E_MAV_DATA_STREAM const> E_MAV_DATA_STREAMConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9af40f4cb9f2b48b204ab94ce486cc7a";
  }

  static const char* value(const ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9af40f4cb9f2b48bULL;
  static const uint64_t static_value2 = 0x204ab94ce486cc7aULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/E_MAV_DATA_STREAM";
  }

  static const char* value(const ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in <function get_timestamp at 0x2710500>\n\
# ENUM: E_MAV_DATA_STREAM\n\
# Description:Data stream IDs. A data stream is not a fixed set of messages, but rather a\n\
#     recommendation to the autopilot software. Individual autopilots may or may not obey\n\
#     the recommended messages.\n\
# Enable all data streams\n\
uint8 E_MAV_DATA_STREAM_ALL = 0\n\
# Enable IMU_RAW, GPS_RAW, GPS_STATUS packets.\n\
uint8 E_MAV_DATA_STREAM_RAW_SENSORS = 1\n\
# Enable GPS_STATUS, CONTROL_STATUS, AUX_STATUS\n\
uint8 E_MAV_DATA_STREAM_EXTENDED_STATUS = 2\n\
# Enable RC_CHANNELS_SCALED, RC_CHANNELS_RAW, SERVO_OUTPUT_RAW\n\
uint8 E_MAV_DATA_STREAM_RC_CHANNELS = 3\n\
# Enable ATTITUDE_CONTROLLER_OUTPUT, POSITION_CONTROLLER_OUTPUT, NAV_CONTROLLER_OUTPUT.\n\
uint8 E_MAV_DATA_STREAM_RAW_CONTROLLER = 4\n\
# Enable LOCAL_POSITION, GLOBAL_POSITION/GLOBAL_POSITION_INT messages.\n\
uint8 E_MAV_DATA_STREAM_POSITION = 6\n\
# Dependent on the autopilot\n\
uint8 E_MAV_DATA_STREAM_EXTRA1 = 10\n\
# Dependent on the autopilot\n\
uint8 E_MAV_DATA_STREAM_EXTRA2 = 11\n\
# Dependent on the autopilot\n\
uint8 E_MAV_DATA_STREAM_EXTRA3 = 12\n\
";
  }

  static const char* value(const ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct E_MAV_DATA_STREAM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mavlink_common::E_MAV_DATA_STREAM_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_E_MAV_DATA_STREAM_H
