/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/E_MAV_MODE_FLAG_DECODE_POSITION.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_E_MAV_MODE_FLAG_DECODE_POSITION_H
#define MAVLINK_COMMON_MESSAGE_E_MAV_MODE_FLAG_DECODE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct E_MAV_MODE_FLAG_DECODE_POSITION_
{
  typedef E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> Type;

  E_MAV_MODE_FLAG_DECODE_POSITION_()
    {
    }
  E_MAV_MODE_FLAG_DECODE_POSITION_(const ContainerAllocator& _alloc)
    {
    }




    enum { E_MAV_MODE_FLAG_DECODE_POSITION_SAFETY = 128 };
     enum { E_MAV_MODE_FLAG_DECODE_POSITION_MANUAL = 64 };
     enum { E_MAV_MODE_FLAG_DECODE_POSITION_HIL = 32 };
     enum { E_MAV_MODE_FLAG_DECODE_POSITION_STABILIZE = 16 };
     enum { E_MAV_MODE_FLAG_DECODE_POSITION_GUIDED = 8 };
     enum { E_MAV_MODE_FLAG_DECODE_POSITION_AUTO = 4 };
     enum { E_MAV_MODE_FLAG_DECODE_POSITION_TEST = 2 };
     enum { E_MAV_MODE_FLAG_DECODE_POSITION_CUSTOM_MODE = 1 };
 

  typedef boost::shared_ptr< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct E_MAV_MODE_FLAG_DECODE_POSITION_

typedef ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<std::allocator<void> > E_MAV_MODE_FLAG_DECODE_POSITION;

typedef boost::shared_ptr< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION > E_MAV_MODE_FLAG_DECODE_POSITIONPtr;
typedef boost::shared_ptr< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION const> E_MAV_MODE_FLAG_DECODE_POSITIONConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8406200a921ca832d0a4c66c1954999";
  }

  static const char* value(const ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8406200a921ca83ULL;
  static const uint64_t static_value2 = 0x2d0a4c66c1954999ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/E_MAV_MODE_FLAG_DECODE_POSITION";
  }

  static const char* value(const ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in <function get_timestamp at 0x2710500>\n\
# ENUM: E_MAV_MODE_FLAG_DECODE_POSITION\n\
# Description:These values encode the bit positions of the decode position. These values can be used to read the value of a flag bit by combining the base_mode variable with AND with the flag position value. The result will be either 0 or 1, depending on if the flag is set or not.\n\
# First bit:  10000000\n\
uint8 E_MAV_MODE_FLAG_DECODE_POSITION_SAFETY = 128\n\
# Second bit: 01000000\n\
uint8 E_MAV_MODE_FLAG_DECODE_POSITION_MANUAL = 64\n\
# Third bit:  00100000\n\
uint8 E_MAV_MODE_FLAG_DECODE_POSITION_HIL = 32\n\
# Fourth bit: 00010000\n\
uint8 E_MAV_MODE_FLAG_DECODE_POSITION_STABILIZE = 16\n\
# Fifth bit:  00001000\n\
uint8 E_MAV_MODE_FLAG_DECODE_POSITION_GUIDED = 8\n\
# Sixt bit:   00000100\n\
uint8 E_MAV_MODE_FLAG_DECODE_POSITION_AUTO = 4\n\
# Seventh bit: 00000010\n\
uint8 E_MAV_MODE_FLAG_DECODE_POSITION_TEST = 2\n\
# Eighth bit: 00000001\n\
uint8 E_MAV_MODE_FLAG_DECODE_POSITION_CUSTOM_MODE = 1\n\
";
  }

  static const char* value(const ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct E_MAV_MODE_FLAG_DECODE_POSITION_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mavlink_common::E_MAV_MODE_FLAG_DECODE_POSITION_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_E_MAV_MODE_FLAG_DECODE_POSITION_H
