/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/E_MAV_SEVERITY.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_E_MAV_SEVERITY_H
#define MAVLINK_COMMON_MESSAGE_E_MAV_SEVERITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct E_MAV_SEVERITY_
{
  typedef E_MAV_SEVERITY_<ContainerAllocator> Type;

  E_MAV_SEVERITY_()
    {
    }
  E_MAV_SEVERITY_(const ContainerAllocator& _alloc)
    {
    }




    enum { E_MAV_SEVERITY_EMERGENCY = 0 };
     enum { E_MAV_SEVERITY_ALERT = 1 };
     enum { E_MAV_SEVERITY_CRITICAL = 2 };
     enum { E_MAV_SEVERITY_ERROR = 3 };
     enum { E_MAV_SEVERITY_WARNING = 4 };
     enum { E_MAV_SEVERITY_NOTICE = 5 };
     enum { E_MAV_SEVERITY_INFO = 6 };
     enum { E_MAV_SEVERITY_DEBUG = 7 };
 

  typedef boost::shared_ptr< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct E_MAV_SEVERITY_

typedef ::mavlink_common::E_MAV_SEVERITY_<std::allocator<void> > E_MAV_SEVERITY;

typedef boost::shared_ptr< ::mavlink_common::E_MAV_SEVERITY > E_MAV_SEVERITYPtr;
typedef boost::shared_ptr< ::mavlink_common::E_MAV_SEVERITY const> E_MAV_SEVERITYConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c9c826d21086ebe7b1ad6435cc94edd";
  }

  static const char* value(const ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c9c826d21086ebeULL;
  static const uint64_t static_value2 = 0x7b1ad6435cc94eddULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/E_MAV_SEVERITY";
  }

  static const char* value(const ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in <function get_timestamp at 0x2710500>\n\
# ENUM: E_MAV_SEVERITY\n\
# Description:Indicates the severity level, generally used for status messages to indicate their relative urgency. Based on RFC-5424 using expanded definitions at: http://www.kiwisyslog.com/kb/info:-syslog-message-levels/.\n\
# System is unusable. This is a \"panic\" condition.\n\
uint8 E_MAV_SEVERITY_EMERGENCY = 0\n\
# Action should be taken immediately. Indicates error in non-critical systems.\n\
uint8 E_MAV_SEVERITY_ALERT = 1\n\
# Action must be taken immediately. Indicates failure in a primary system.\n\
uint8 E_MAV_SEVERITY_CRITICAL = 2\n\
# Indicates an error in secondary/redundant systems.\n\
uint8 E_MAV_SEVERITY_ERROR = 3\n\
# Indicates about a possible future error if this is not resolved within a given timeframe. Example would be a low battery warning.\n\
uint8 E_MAV_SEVERITY_WARNING = 4\n\
# An unusual event has occured, though not an error condition. This should be investigated for the root cause.\n\
uint8 E_MAV_SEVERITY_NOTICE = 5\n\
# Normal operational messages. Useful for logging. No action is required for these messages.\n\
uint8 E_MAV_SEVERITY_INFO = 6\n\
# Useful non-operational messages that can assist in debugging. These should not occur during normal operation.\n\
uint8 E_MAV_SEVERITY_DEBUG = 7\n\
";
  }

  static const char* value(const ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct E_MAV_SEVERITY_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mavlink_common::E_MAV_SEVERITY_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_E_MAV_SEVERITY_H
