/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/FILE_TRANSFER_START.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_FILE_TRANSFER_START_H
#define MAVLINK_COMMON_MESSAGE_FILE_TRANSFER_START_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct FILE_TRANSFER_START_
{
  typedef FILE_TRANSFER_START_<ContainerAllocator> Type;

  FILE_TRANSFER_START_()
    : sysid(0)
    , compid(0)
    , transfer_uid(0)
    , dest_path()
    , direction(0)
    , file_size(0)
    , flags(0)  {
      dest_path.assign(0);
  }
  FILE_TRANSFER_START_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , transfer_uid(0)
    , dest_path()
    , direction(0)
    , file_size(0)
    , flags(0)  {
      dest_path.assign(0);
  }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint64_t _transfer_uid_type;
  _transfer_uid_type transfer_uid;

   typedef boost::array<uint8_t, 240>  _dest_path_type;
  _dest_path_type dest_path;

   typedef uint8_t _direction_type;
  _direction_type direction;

   typedef uint32_t _file_size_type;
  _file_size_type file_size;

   typedef uint8_t _flags_type;
  _flags_type flags;


    enum { ID = 110 };
 

  typedef boost::shared_ptr< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct FILE_TRANSFER_START_

typedef ::mavlink_common::FILE_TRANSFER_START_<std::allocator<void> > FILE_TRANSFER_START;

typedef boost::shared_ptr< ::mavlink_common::FILE_TRANSFER_START > FILE_TRANSFER_STARTPtr;
typedef boost::shared_ptr< ::mavlink_common::FILE_TRANSFER_START const> FILE_TRANSFER_STARTConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ef159785764c39dcf4d748762b835b3";
  }

  static const char* value(const ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ef159785764c39dULL;
  static const uint64_t static_value2 = 0xcf4d748762b835b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/FILE_TRANSFER_START";
  }

  static const char* value(const ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.910536\n\
# MESSAGE: FILE_TRANSFER_START\n\
# Description:Begin file transfer\n\
uint8 ID = 110\n\
uint8 sysid\n\
uint8 compid\n\
uint64 transfer_uid\n\
char[240] dest_path\n\
uint8 direction\n\
uint32 file_size\n\
uint8 flags\n\
";
  }

  static const char* value(const ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.transfer_uid);
      stream.next(m.dest_path);
      stream.next(m.direction);
      stream.next(m.file_size);
      stream.next(m.flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FILE_TRANSFER_START_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::FILE_TRANSFER_START_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "transfer_uid: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.transfer_uid);
    s << indent << "dest_path[]" << std::endl;
    for (size_t i = 0; i < v.dest_path.size(); ++i)
    {
      s << indent << "  dest_path[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.dest_path[i]);
    }
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "file_size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.file_size);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_FILE_TRANSFER_START_H
