/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/GLOBAL_VISION_POSITION_ESTIMATE.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_GLOBAL_VISION_POSITION_ESTIMATE_H
#define MAVLINK_COMMON_MESSAGE_GLOBAL_VISION_POSITION_ESTIMATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct GLOBAL_VISION_POSITION_ESTIMATE_
{
  typedef GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> Type;

  GLOBAL_VISION_POSITION_ESTIMATE_()
    : sysid(0)
    , compid(0)
    , usec(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  GLOBAL_VISION_POSITION_ESTIMATE_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , usec(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint64_t _usec_type;
  _usec_type usec;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;


    enum { ID = 101 };
 

  typedef boost::shared_ptr< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GLOBAL_VISION_POSITION_ESTIMATE_

typedef ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<std::allocator<void> > GLOBAL_VISION_POSITION_ESTIMATE;

typedef boost::shared_ptr< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE > GLOBAL_VISION_POSITION_ESTIMATEPtr;
typedef boost::shared_ptr< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE const> GLOBAL_VISION_POSITION_ESTIMATEConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a2e3363bfdb4db485be621397a42389";
  }

  static const char* value(const ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a2e3363bfdb4db4ULL;
  static const uint64_t static_value2 = 0x85be621397a42389ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/GLOBAL_VISION_POSITION_ESTIMATE";
  }

  static const char* value(const ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.910210\n\
# MESSAGE: GLOBAL_VISION_POSITION_ESTIMATE\n\
uint8 ID = 101\n\
uint8 sysid\n\
uint8 compid\n\
uint64 usec\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
";
  }

  static const char* value(const ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.usec);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GLOBAL_VISION_POSITION_ESTIMATE_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::GLOBAL_VISION_POSITION_ESTIMATE_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "usec: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.usec);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_GLOBAL_VISION_POSITION_ESTIMATE_H
