/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/GLOBAL_POSITION_INT.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_GLOBAL_POSITION_INT_H
#define MAVLINK_COMMON_MESSAGE_GLOBAL_POSITION_INT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct GLOBAL_POSITION_INT_
{
  typedef GLOBAL_POSITION_INT_<ContainerAllocator> Type;

  GLOBAL_POSITION_INT_()
    : sysid(0)
    , compid(0)
    , time_boot_ms(0)
    , lat(0)
    , lon(0)
    , alt(0)
    , relative_alt(0)
    , vx(0)
    , vy(0)
    , vz(0)
    , hdg(0)  {
    }
  GLOBAL_POSITION_INT_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , time_boot_ms(0)
    , lat(0)
    , lon(0)
    , alt(0)
    , relative_alt(0)
    , vx(0)
    , vy(0)
    , vz(0)
    , hdg(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint32_t _time_boot_ms_type;
  _time_boot_ms_type time_boot_ms;

   typedef int32_t _lat_type;
  _lat_type lat;

   typedef int32_t _lon_type;
  _lon_type lon;

   typedef int32_t _alt_type;
  _alt_type alt;

   typedef int32_t _relative_alt_type;
  _relative_alt_type relative_alt;

   typedef int16_t _vx_type;
  _vx_type vx;

   typedef int16_t _vy_type;
  _vy_type vy;

   typedef int16_t _vz_type;
  _vz_type vz;

   typedef uint16_t _hdg_type;
  _hdg_type hdg;


    enum { ID = 33 };
 

  typedef boost::shared_ptr< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GLOBAL_POSITION_INT_

typedef ::mavlink_common::GLOBAL_POSITION_INT_<std::allocator<void> > GLOBAL_POSITION_INT;

typedef boost::shared_ptr< ::mavlink_common::GLOBAL_POSITION_INT > GLOBAL_POSITION_INTPtr;
typedef boost::shared_ptr< ::mavlink_common::GLOBAL_POSITION_INT const> GLOBAL_POSITION_INTConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3a237f463f1b3b326eadc0825f31f4c";
  }

  static const char* value(const ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3a237f463f1b3b3ULL;
  static const uint64_t static_value2 = 0x26eadc0825f31f4cULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/GLOBAL_POSITION_INT";
  }

  static const char* value(const ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.907475\n\
# MESSAGE: GLOBAL_POSITION_INT\n\
# Description:The filtered global position (e.g. fused GPS and accelerometers). The position is in GPS-frame (right-handed, Z-up). It\n\
#               is designed as scaled integer message since the resolution of float is not sufficient.\n\
uint8 ID = 33\n\
uint8 sysid\n\
uint8 compid\n\
uint32 time_boot_ms\n\
int32 lat\n\
int32 lon\n\
int32 alt\n\
int32 relative_alt\n\
int16 vx\n\
int16 vy\n\
int16 vz\n\
uint16 hdg\n\
";
  }

  static const char* value(const ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.time_boot_ms);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.alt);
      stream.next(m.relative_alt);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.hdg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GLOBAL_POSITION_INT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::GLOBAL_POSITION_INT_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "time_boot_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_boot_ms);
    s << indent << "lat: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lon);
    s << indent << "alt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.alt);
    s << indent << "relative_alt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.relative_alt);
    s << indent << "vx: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vz);
    s << indent << "hdg: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.hdg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_GLOBAL_POSITION_INT_H
