/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/GPS_STATUS.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_GPS_STATUS_H
#define MAVLINK_COMMON_MESSAGE_GPS_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct GPS_STATUS_
{
  typedef GPS_STATUS_<ContainerAllocator> Type;

  GPS_STATUS_()
    : sysid(0)
    , compid(0)
    , satellites_visible(0)
    , satellite_prn()
    , satellite_used()
    , satellite_elevation()
    , satellite_azimuth()
    , satellite_snr()  {
      satellite_prn.assign(0);

      satellite_used.assign(0);

      satellite_elevation.assign(0);

      satellite_azimuth.assign(0);

      satellite_snr.assign(0);
  }
  GPS_STATUS_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , satellites_visible(0)
    , satellite_prn()
    , satellite_used()
    , satellite_elevation()
    , satellite_azimuth()
    , satellite_snr()  {
      satellite_prn.assign(0);

      satellite_used.assign(0);

      satellite_elevation.assign(0);

      satellite_azimuth.assign(0);

      satellite_snr.assign(0);
  }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _satellites_visible_type;
  _satellites_visible_type satellites_visible;

   typedef boost::array<uint8_t, 20>  _satellite_prn_type;
  _satellite_prn_type satellite_prn;

   typedef boost::array<uint8_t, 20>  _satellite_used_type;
  _satellite_used_type satellite_used;

   typedef boost::array<uint8_t, 20>  _satellite_elevation_type;
  _satellite_elevation_type satellite_elevation;

   typedef boost::array<uint8_t, 20>  _satellite_azimuth_type;
  _satellite_azimuth_type satellite_azimuth;

   typedef boost::array<uint8_t, 20>  _satellite_snr_type;
  _satellite_snr_type satellite_snr;


    enum { ID = 25 };
 

  typedef boost::shared_ptr< ::mavlink_common::GPS_STATUS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::GPS_STATUS_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GPS_STATUS_

typedef ::mavlink_common::GPS_STATUS_<std::allocator<void> > GPS_STATUS;

typedef boost::shared_ptr< ::mavlink_common::GPS_STATUS > GPS_STATUSPtr;
typedef boost::shared_ptr< ::mavlink_common::GPS_STATUS const> GPS_STATUSConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::GPS_STATUS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::GPS_STATUS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::GPS_STATUS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::GPS_STATUS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6c5ba137f034801a81e81f9f0c19c16";
  }

  static const char* value(const ::mavlink_common::GPS_STATUS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6c5ba137f034801ULL;
  static const uint64_t static_value2 = 0xa81e81f9f0c19c16ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/GPS_STATUS";
  }

  static const char* value(const ::mavlink_common::GPS_STATUS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.906861\n\
# MESSAGE: GPS_STATUS\n\
# Description:The positioning status, as reported by GPS. This message is intended to display status information about each satellite visible to the receiver. See message GLOBAL_POSITION for the global position estimate. This message can contain information for up to 20 satellites.\n\
uint8 ID = 25\n\
uint8 sysid\n\
uint8 compid\n\
uint8 satellites_visible\n\
uint8[20] satellite_prn\n\
uint8[20] satellite_used\n\
uint8[20] satellite_elevation\n\
uint8[20] satellite_azimuth\n\
uint8[20] satellite_snr\n\
";
  }

  static const char* value(const ::mavlink_common::GPS_STATUS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.satellites_visible);
      stream.next(m.satellite_prn);
      stream.next(m.satellite_used);
      stream.next(m.satellite_elevation);
      stream.next(m.satellite_azimuth);
      stream.next(m.satellite_snr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GPS_STATUS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::GPS_STATUS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::GPS_STATUS_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "satellites_visible: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.satellites_visible);
    s << indent << "satellite_prn[]" << std::endl;
    for (size_t i = 0; i < v.satellite_prn.size(); ++i)
    {
      s << indent << "  satellite_prn[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.satellite_prn[i]);
    }
    s << indent << "satellite_used[]" << std::endl;
    for (size_t i = 0; i < v.satellite_used.size(); ++i)
    {
      s << indent << "  satellite_used[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.satellite_used[i]);
    }
    s << indent << "satellite_elevation[]" << std::endl;
    for (size_t i = 0; i < v.satellite_elevation.size(); ++i)
    {
      s << indent << "  satellite_elevation[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.satellite_elevation[i]);
    }
    s << indent << "satellite_azimuth[]" << std::endl;
    for (size_t i = 0; i < v.satellite_azimuth.size(); ++i)
    {
      s << indent << "  satellite_azimuth[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.satellite_azimuth[i]);
    }
    s << indent << "satellite_snr[]" << std::endl;
    for (size_t i = 0; i < v.satellite_snr.size(); ++i)
    {
      s << indent << "  satellite_snr[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.satellite_snr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_GPS_STATUS_H
