/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/HIL_CONTROLS.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_HIL_CONTROLS_H
#define MAVLINK_COMMON_MESSAGE_HIL_CONTROLS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct HIL_CONTROLS_
{
  typedef HIL_CONTROLS_<ContainerAllocator> Type;

  HIL_CONTROLS_()
    : sysid(0)
    , compid(0)
    , time_usec(0)
    , roll_ailerons(0.0)
    , pitch_elevator(0.0)
    , yaw_rudder(0.0)
    , throttle(0.0)
    , aux1(0.0)
    , aux2(0.0)
    , aux3(0.0)
    , aux4(0.0)
    , mode(0)
    , nav_mode(0)  {
    }
  HIL_CONTROLS_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , time_usec(0)
    , roll_ailerons(0.0)
    , pitch_elevator(0.0)
    , yaw_rudder(0.0)
    , throttle(0.0)
    , aux1(0.0)
    , aux2(0.0)
    , aux3(0.0)
    , aux4(0.0)
    , mode(0)
    , nav_mode(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint64_t _time_usec_type;
  _time_usec_type time_usec;

   typedef float _roll_ailerons_type;
  _roll_ailerons_type roll_ailerons;

   typedef float _pitch_elevator_type;
  _pitch_elevator_type pitch_elevator;

   typedef float _yaw_rudder_type;
  _yaw_rudder_type yaw_rudder;

   typedef float _throttle_type;
  _throttle_type throttle;

   typedef float _aux1_type;
  _aux1_type aux1;

   typedef float _aux2_type;
  _aux2_type aux2;

   typedef float _aux3_type;
  _aux3_type aux3;

   typedef float _aux4_type;
  _aux4_type aux4;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _nav_mode_type;
  _nav_mode_type nav_mode;


    enum { ID = 91 };
 

  typedef boost::shared_ptr< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct HIL_CONTROLS_

typedef ::mavlink_common::HIL_CONTROLS_<std::allocator<void> > HIL_CONTROLS;

typedef boost::shared_ptr< ::mavlink_common::HIL_CONTROLS > HIL_CONTROLSPtr;
typedef boost::shared_ptr< ::mavlink_common::HIL_CONTROLS const> HIL_CONTROLSConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e815da09bbc4cca359acdcec587bf987";
  }

  static const char* value(const ::mavlink_common::HIL_CONTROLS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe815da09bbc4cca3ULL;
  static const uint64_t static_value2 = 0x59acdcec587bf987ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/HIL_CONTROLS";
  }

  static const char* value(const ::mavlink_common::HIL_CONTROLS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.909982\n\
# MESSAGE: HIL_CONTROLS\n\
# Description:Sent from autopilot to simulation. Hardware in the loop control outputs\n\
uint8 ID = 91\n\
uint8 sysid\n\
uint8 compid\n\
uint64 time_usec\n\
float32 roll_ailerons\n\
float32 pitch_elevator\n\
float32 yaw_rudder\n\
float32 throttle\n\
float32 aux1\n\
float32 aux2\n\
float32 aux3\n\
float32 aux4\n\
uint8 mode\n\
uint8 nav_mode\n\
";
  }

  static const char* value(const ::mavlink_common::HIL_CONTROLS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.time_usec);
      stream.next(m.roll_ailerons);
      stream.next(m.pitch_elevator);
      stream.next(m.yaw_rudder);
      stream.next(m.throttle);
      stream.next(m.aux1);
      stream.next(m.aux2);
      stream.next(m.aux3);
      stream.next(m.aux4);
      stream.next(m.mode);
      stream.next(m.nav_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HIL_CONTROLS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::HIL_CONTROLS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::HIL_CONTROLS_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "time_usec: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time_usec);
    s << indent << "roll_ailerons: ";
    Printer<float>::stream(s, indent + "  ", v.roll_ailerons);
    s << indent << "pitch_elevator: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_elevator);
    s << indent << "yaw_rudder: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rudder);
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "aux1: ";
    Printer<float>::stream(s, indent + "  ", v.aux1);
    s << indent << "aux2: ";
    Printer<float>::stream(s, indent + "  ", v.aux2);
    s << indent << "aux3: ";
    Printer<float>::stream(s, indent + "  ", v.aux3);
    s << indent << "aux4: ";
    Printer<float>::stream(s, indent + "  ", v.aux4);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "nav_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nav_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_HIL_CONTROLS_H
