/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/HIL_STATE.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_HIL_STATE_H
#define MAVLINK_COMMON_MESSAGE_HIL_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct HIL_STATE_
{
  typedef HIL_STATE_<ContainerAllocator> Type;

  HIL_STATE_()
    : sysid(0)
    , compid(0)
    , time_usec(0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , rollspeed(0.0)
    , pitchspeed(0.0)
    , yawspeed(0.0)
    , lat(0)
    , lon(0)
    , alt(0)
    , vx(0)
    , vy(0)
    , vz(0)
    , xacc(0)
    , yacc(0)
    , zacc(0)  {
    }
  HIL_STATE_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , time_usec(0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , rollspeed(0.0)
    , pitchspeed(0.0)
    , yawspeed(0.0)
    , lat(0)
    , lon(0)
    , alt(0)
    , vx(0)
    , vy(0)
    , vz(0)
    , xacc(0)
    , yacc(0)
    , zacc(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint64_t _time_usec_type;
  _time_usec_type time_usec;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _rollspeed_type;
  _rollspeed_type rollspeed;

   typedef float _pitchspeed_type;
  _pitchspeed_type pitchspeed;

   typedef float _yawspeed_type;
  _yawspeed_type yawspeed;

   typedef int32_t _lat_type;
  _lat_type lat;

   typedef int32_t _lon_type;
  _lon_type lon;

   typedef int32_t _alt_type;
  _alt_type alt;

   typedef int16_t _vx_type;
  _vx_type vx;

   typedef int16_t _vy_type;
  _vy_type vy;

   typedef int16_t _vz_type;
  _vz_type vz;

   typedef int16_t _xacc_type;
  _xacc_type xacc;

   typedef int16_t _yacc_type;
  _yacc_type yacc;

   typedef int16_t _zacc_type;
  _zacc_type zacc;


    enum { ID = 90 };
 

  typedef boost::shared_ptr< ::mavlink_common::HIL_STATE_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::HIL_STATE_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct HIL_STATE_

typedef ::mavlink_common::HIL_STATE_<std::allocator<void> > HIL_STATE;

typedef boost::shared_ptr< ::mavlink_common::HIL_STATE > HIL_STATEPtr;
typedef boost::shared_ptr< ::mavlink_common::HIL_STATE const> HIL_STATEConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::HIL_STATE_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::HIL_STATE_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::HIL_STATE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::HIL_STATE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::HIL_STATE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::HIL_STATE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::HIL_STATE_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::HIL_STATE_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::HIL_STATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f59632974015c16b61ee8c8e85647385";
  }

  static const char* value(const ::mavlink_common::HIL_STATE_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf59632974015c16bULL;
  static const uint64_t static_value2 = 0x61ee8c8e85647385ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::HIL_STATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/HIL_STATE";
  }

  static const char* value(const ::mavlink_common::HIL_STATE_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::HIL_STATE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.909917\n\
# MESSAGE: HIL_STATE\n\
# Description:Sent from simulation to autopilot. This packet is useful for high throughput applications such as hardware in the loop simulations.\n\
uint8 ID = 90\n\
uint8 sysid\n\
uint8 compid\n\
uint64 time_usec\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
float32 rollspeed\n\
float32 pitchspeed\n\
float32 yawspeed\n\
int32 lat\n\
int32 lon\n\
int32 alt\n\
int16 vx\n\
int16 vy\n\
int16 vz\n\
int16 xacc\n\
int16 yacc\n\
int16 zacc\n\
";
  }

  static const char* value(const ::mavlink_common::HIL_STATE_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::HIL_STATE_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.time_usec);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.rollspeed);
      stream.next(m.pitchspeed);
      stream.next(m.yawspeed);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.alt);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.xacc);
      stream.next(m.yacc);
      stream.next(m.zacc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HIL_STATE_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::HIL_STATE_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::HIL_STATE_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "time_usec: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time_usec);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "rollspeed: ";
    Printer<float>::stream(s, indent + "  ", v.rollspeed);
    s << indent << "pitchspeed: ";
    Printer<float>::stream(s, indent + "  ", v.pitchspeed);
    s << indent << "yawspeed: ";
    Printer<float>::stream(s, indent + "  ", v.yawspeed);
    s << indent << "lat: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lon);
    s << indent << "alt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.alt);
    s << indent << "vx: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vz);
    s << indent << "xacc: ";
    Printer<int16_t>::stream(s, indent + "  ", v.xacc);
    s << indent << "yacc: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yacc);
    s << indent << "zacc: ";
    Printer<int16_t>::stream(s, indent + "  ", v.zacc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_HIL_STATE_H
