/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/MANUAL_CONTROL.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_MANUAL_CONTROL_H
#define MAVLINK_COMMON_MESSAGE_MANUAL_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct MANUAL_CONTROL_
{
  typedef MANUAL_CONTROL_<ContainerAllocator> Type;

  MANUAL_CONTROL_()
    : sysid(0)
    , compid(0)
    , target(0)
    , x(0)
    , y(0)
    , z(0)
    , r(0)
    , buttons(0)  {
    }
  MANUAL_CONTROL_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , target(0)
    , x(0)
    , y(0)
    , z(0)
    , r(0)
    , buttons(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _target_type;
  _target_type target;

   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _z_type;
  _z_type z;

   typedef int16_t _r_type;
  _r_type r;

   typedef uint16_t _buttons_type;
  _buttons_type buttons;


    enum { ID = 69 };
 

  typedef boost::shared_ptr< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MANUAL_CONTROL_

typedef ::mavlink_common::MANUAL_CONTROL_<std::allocator<void> > MANUAL_CONTROL;

typedef boost::shared_ptr< ::mavlink_common::MANUAL_CONTROL > MANUAL_CONTROLPtr;
typedef boost::shared_ptr< ::mavlink_common::MANUAL_CONTROL const> MANUAL_CONTROLConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "618b35cff902db66066d15efe7e56bbd";
  }

  static const char* value(const ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x618b35cff902db66ULL;
  static const uint64_t static_value2 = 0x066d15efe7e56bbdULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/MANUAL_CONTROL";
  }

  static const char* value(const ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.909451\n\
# MESSAGE: MANUAL_CONTROL\n\
# Description:This message provides an API for manually controlling the vehicle using standard joystick axes nomenclature, along with a joystick-like input device. Unused axes can be disabled an buttons are also transmit as boolean values of their \n\
uint8 ID = 69\n\
uint8 sysid\n\
uint8 compid\n\
uint8 target\n\
int16 x\n\
int16 y\n\
int16 z\n\
int16 r\n\
uint16 buttons\n\
";
  }

  static const char* value(const ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.target);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.r);
      stream.next(m.buttons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MANUAL_CONTROL_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::MANUAL_CONTROL_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "target: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target);
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.z);
    s << indent << "r: ";
    Printer<int16_t>::stream(s, indent + "  ", v.r);
    s << indent << "buttons: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.buttons);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_MANUAL_CONTROL_H
