/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/MEMORY_VECT.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_MEMORY_VECT_H
#define MAVLINK_COMMON_MESSAGE_MEMORY_VECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct MEMORY_VECT_
{
  typedef MEMORY_VECT_<ContainerAllocator> Type;

  MEMORY_VECT_()
    : sysid(0)
    , compid(0)
    , address(0)
    , ver(0)
    , type(0)
    , value()  {
      value.assign(0);
  }
  MEMORY_VECT_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , address(0)
    , ver(0)
    , type(0)
    , value()  {
      value.assign(0);
  }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint16_t _address_type;
  _address_type address;

   typedef uint8_t _ver_type;
  _ver_type ver;

   typedef uint8_t _type_type;
  _type_type type;

   typedef boost::array<int8_t, 32>  _value_type;
  _value_type value;


    enum { ID = 249 };
 

  typedef boost::shared_ptr< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MEMORY_VECT_

typedef ::mavlink_common::MEMORY_VECT_<std::allocator<void> > MEMORY_VECT;

typedef boost::shared_ptr< ::mavlink_common::MEMORY_VECT > MEMORY_VECTPtr;
typedef boost::shared_ptr< ::mavlink_common::MEMORY_VECT const> MEMORY_VECTConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::MEMORY_VECT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c126e7e94161593886a3737b438d9633";
  }

  static const char* value(const ::mavlink_common::MEMORY_VECT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc126e7e941615938ULL;
  static const uint64_t static_value2 = 0x86a3737b438d9633ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/MEMORY_VECT";
  }

  static const char* value(const ::mavlink_common::MEMORY_VECT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.910879\n\
# MESSAGE: MEMORY_VECT\n\
# Description:Send raw controller memory. The use of this message is discouraged for normal packets, but a quite efficient way for testing new messages and getting experimental debug output.\n\
uint8 ID = 249\n\
uint8 sysid\n\
uint8 compid\n\
uint16 address\n\
uint8 ver\n\
uint8 type\n\
int8[32] value\n\
";
  }

  static const char* value(const ::mavlink_common::MEMORY_VECT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.address);
      stream.next(m.ver);
      stream.next(m.type);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MEMORY_VECT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::MEMORY_VECT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::MEMORY_VECT_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "address: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.address);
    s << indent << "ver: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ver);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_MEMORY_VECT_H
