/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/NAMED_VALUE_FLOAT.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_NAMED_VALUE_FLOAT_H
#define MAVLINK_COMMON_MESSAGE_NAMED_VALUE_FLOAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct NAMED_VALUE_FLOAT_
{
  typedef NAMED_VALUE_FLOAT_<ContainerAllocator> Type;

  NAMED_VALUE_FLOAT_()
    : sysid(0)
    , compid(0)
    , time_boot_ms(0)
    , name()
    , value(0.0)  {
      name.assign(0);
  }
  NAMED_VALUE_FLOAT_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , time_boot_ms(0)
    , name()
    , value(0.0)  {
      name.assign(0);
  }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint32_t _time_boot_ms_type;
  _time_boot_ms_type time_boot_ms;

   typedef boost::array<uint8_t, 10>  _name_type;
  _name_type name;

   typedef float _value_type;
  _value_type value;


    enum { ID = 251 };
 

  typedef boost::shared_ptr< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct NAMED_VALUE_FLOAT_

typedef ::mavlink_common::NAMED_VALUE_FLOAT_<std::allocator<void> > NAMED_VALUE_FLOAT;

typedef boost::shared_ptr< ::mavlink_common::NAMED_VALUE_FLOAT > NAMED_VALUE_FLOATPtr;
typedef boost::shared_ptr< ::mavlink_common::NAMED_VALUE_FLOAT const> NAMED_VALUE_FLOATConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "571675dbb4f69b232fcf6182c1e48adf";
  }

  static const char* value(const ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x571675dbb4f69b23ULL;
  static const uint64_t static_value2 = 0x2fcf6182c1e48adfULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/NAMED_VALUE_FLOAT";
  }

  static const char* value(const ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.910991\n\
# MESSAGE: NAMED_VALUE_FLOAT\n\
# Description:Send a key-value pair as float. The use of this message is discouraged for normal packets, but a quite efficient way for testing new messages and getting experimental debug output.\n\
uint8 ID = 251\n\
uint8 sysid\n\
uint8 compid\n\
uint32 time_boot_ms\n\
char[10] name\n\
float32 value\n\
";
  }

  static const char* value(const ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.time_boot_ms);
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct NAMED_VALUE_FLOAT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::NAMED_VALUE_FLOAT_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "time_boot_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_boot_ms);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_NAMED_VALUE_FLOAT_H
