/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/PARAM_SET.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_PARAM_SET_H
#define MAVLINK_COMMON_MESSAGE_PARAM_SET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct PARAM_SET_
{
  typedef PARAM_SET_<ContainerAllocator> Type;

  PARAM_SET_()
    : sysid(0)
    , compid(0)
    , target_system(0)
    , target_component(0)
    , param_id()
    , param_value(0.0)
    , param_type(0)  {
      param_id.assign(0);
  }
  PARAM_SET_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , target_system(0)
    , target_component(0)
    , param_id()
    , param_value(0.0)
    , param_type(0)  {
      param_id.assign(0);
  }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _target_system_type;
  _target_system_type target_system;

   typedef uint8_t _target_component_type;
  _target_component_type target_component;

   typedef boost::array<uint8_t, 16>  _param_id_type;
  _param_id_type param_id;

   typedef float _param_value_type;
  _param_value_type param_value;

   typedef uint8_t _param_type_type;
  _param_type_type param_type;


    enum { ID = 23 };
 

  typedef boost::shared_ptr< ::mavlink_common::PARAM_SET_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::PARAM_SET_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct PARAM_SET_

typedef ::mavlink_common::PARAM_SET_<std::allocator<void> > PARAM_SET;

typedef boost::shared_ptr< ::mavlink_common::PARAM_SET > PARAM_SETPtr;
typedef boost::shared_ptr< ::mavlink_common::PARAM_SET const> PARAM_SETConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::PARAM_SET_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::PARAM_SET_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::PARAM_SET_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::PARAM_SET_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::PARAM_SET_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::PARAM_SET_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::PARAM_SET_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::PARAM_SET_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::PARAM_SET_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c66eb3651fcdf84231c70c3fabca6cdd";
  }

  static const char* value(const ::mavlink_common::PARAM_SET_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc66eb3651fcdf842ULL;
  static const uint64_t static_value2 = 0x31c70c3fabca6cddULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::PARAM_SET_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/PARAM_SET";
  }

  static const char* value(const ::mavlink_common::PARAM_SET_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::PARAM_SET_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.906736\n\
# MESSAGE: PARAM_SET\n\
# Description:Set a parameter value TEMPORARILY to RAM. It will be reset to default on system reboot. Send the ACTION MAV_ACTION_STORAGE_WRITE to PERMANENTLY write the RAM contents to EEPROM. IMPORTANT: The receiving component should acknowledge the new parameter value by sending a param_value message to all communication partners. This will also ensure that multiple GCS all have an up-to-date list of all parameters. If the sending GCS did not receive a PARAM_VALUE message within its timeout time, it should re-send the PARAM_SET message.\n\
uint8 ID = 23\n\
uint8 sysid\n\
uint8 compid\n\
uint8 target_system\n\
uint8 target_component\n\
char[16] param_id\n\
float32 param_value\n\
uint8 param_type\n\
";
  }

  static const char* value(const ::mavlink_common::PARAM_SET_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::PARAM_SET_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.target_system);
      stream.next(m.target_component);
      stream.next(m.param_id);
      stream.next(m.param_value);
      stream.next(m.param_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PARAM_SET_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::PARAM_SET_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::PARAM_SET_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "target_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_system);
    s << indent << "target_component: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_component);
    s << indent << "param_id[]" << std::endl;
    for (size_t i = 0; i < v.param_id.size(); ++i)
    {
      s << indent << "  param_id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.param_id[i]);
    }
    s << indent << "param_value: ";
    Printer<float>::stream(s, indent + "  ", v.param_value);
    s << indent << "param_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.param_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_PARAM_SET_H
