/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/RC_CHANNELS_SCALED.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_RC_CHANNELS_SCALED_H
#define MAVLINK_COMMON_MESSAGE_RC_CHANNELS_SCALED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct RC_CHANNELS_SCALED_
{
  typedef RC_CHANNELS_SCALED_<ContainerAllocator> Type;

  RC_CHANNELS_SCALED_()
    : sysid(0)
    , compid(0)
    , time_boot_ms(0)
    , port(0)
    , chan1_scaled(0)
    , chan2_scaled(0)
    , chan3_scaled(0)
    , chan4_scaled(0)
    , chan5_scaled(0)
    , chan6_scaled(0)
    , chan7_scaled(0)
    , chan8_scaled(0)
    , rssi(0)  {
    }
  RC_CHANNELS_SCALED_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , time_boot_ms(0)
    , port(0)
    , chan1_scaled(0)
    , chan2_scaled(0)
    , chan3_scaled(0)
    , chan4_scaled(0)
    , chan5_scaled(0)
    , chan6_scaled(0)
    , chan7_scaled(0)
    , chan8_scaled(0)
    , rssi(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint32_t _time_boot_ms_type;
  _time_boot_ms_type time_boot_ms;

   typedef uint8_t _port_type;
  _port_type port;

   typedef int16_t _chan1_scaled_type;
  _chan1_scaled_type chan1_scaled;

   typedef int16_t _chan2_scaled_type;
  _chan2_scaled_type chan2_scaled;

   typedef int16_t _chan3_scaled_type;
  _chan3_scaled_type chan3_scaled;

   typedef int16_t _chan4_scaled_type;
  _chan4_scaled_type chan4_scaled;

   typedef int16_t _chan5_scaled_type;
  _chan5_scaled_type chan5_scaled;

   typedef int16_t _chan6_scaled_type;
  _chan6_scaled_type chan6_scaled;

   typedef int16_t _chan7_scaled_type;
  _chan7_scaled_type chan7_scaled;

   typedef int16_t _chan8_scaled_type;
  _chan8_scaled_type chan8_scaled;

   typedef uint8_t _rssi_type;
  _rssi_type rssi;


    enum { ID = 34 };
 

  typedef boost::shared_ptr< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct RC_CHANNELS_SCALED_

typedef ::mavlink_common::RC_CHANNELS_SCALED_<std::allocator<void> > RC_CHANNELS_SCALED;

typedef boost::shared_ptr< ::mavlink_common::RC_CHANNELS_SCALED > RC_CHANNELS_SCALEDPtr;
typedef boost::shared_ptr< ::mavlink_common::RC_CHANNELS_SCALED const> RC_CHANNELS_SCALEDConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "701983f4cd847b0d6b4088558f196f4a";
  }

  static const char* value(const ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x701983f4cd847b0dULL;
  static const uint64_t static_value2 = 0x6b4088558f196f4aULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/RC_CHANNELS_SCALED";
  }

  static const char* value(const ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.907536\n\
# MESSAGE: RC_CHANNELS_SCALED\n\
# Description:The scaled values of the RC channels received. (-100%) -10000, (0%) 0, (100%) 10000. Channels that are inactive should be set to 65535.\n\
uint8 ID = 34\n\
uint8 sysid\n\
uint8 compid\n\
uint32 time_boot_ms\n\
uint8 port\n\
int16 chan1_scaled\n\
int16 chan2_scaled\n\
int16 chan3_scaled\n\
int16 chan4_scaled\n\
int16 chan5_scaled\n\
int16 chan6_scaled\n\
int16 chan7_scaled\n\
int16 chan8_scaled\n\
uint8 rssi\n\
";
  }

  static const char* value(const ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.time_boot_ms);
      stream.next(m.port);
      stream.next(m.chan1_scaled);
      stream.next(m.chan2_scaled);
      stream.next(m.chan3_scaled);
      stream.next(m.chan4_scaled);
      stream.next(m.chan5_scaled);
      stream.next(m.chan6_scaled);
      stream.next(m.chan7_scaled);
      stream.next(m.chan8_scaled);
      stream.next(m.rssi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RC_CHANNELS_SCALED_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::RC_CHANNELS_SCALED_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "time_boot_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_boot_ms);
    s << indent << "port: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.port);
    s << indent << "chan1_scaled: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chan1_scaled);
    s << indent << "chan2_scaled: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chan2_scaled);
    s << indent << "chan3_scaled: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chan3_scaled);
    s << indent << "chan4_scaled: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chan4_scaled);
    s << indent << "chan5_scaled: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chan5_scaled);
    s << indent << "chan6_scaled: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chan6_scaled);
    s << indent << "chan7_scaled: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chan7_scaled);
    s << indent << "chan8_scaled: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chan8_scaled);
    s << indent << "rssi: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rssi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_RC_CHANNELS_SCALED_H
