/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/REQUEST_DATA_STREAM.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_REQUEST_DATA_STREAM_H
#define MAVLINK_COMMON_MESSAGE_REQUEST_DATA_STREAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct REQUEST_DATA_STREAM_
{
  typedef REQUEST_DATA_STREAM_<ContainerAllocator> Type;

  REQUEST_DATA_STREAM_()
    : sysid(0)
    , compid(0)
    , target_system(0)
    , target_component(0)
    , req_stream_id(0)
    , req_message_rate(0)
    , start_stop(0)  {
    }
  REQUEST_DATA_STREAM_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , target_system(0)
    , target_component(0)
    , req_stream_id(0)
    , req_message_rate(0)
    , start_stop(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _target_system_type;
  _target_system_type target_system;

   typedef uint8_t _target_component_type;
  _target_component_type target_component;

   typedef uint8_t _req_stream_id_type;
  _req_stream_id_type req_stream_id;

   typedef uint16_t _req_message_rate_type;
  _req_message_rate_type req_message_rate;

   typedef uint8_t _start_stop_type;
  _start_stop_type start_stop;


    enum { ID = 66 };
 

  typedef boost::shared_ptr< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct REQUEST_DATA_STREAM_

typedef ::mavlink_common::REQUEST_DATA_STREAM_<std::allocator<void> > REQUEST_DATA_STREAM;

typedef boost::shared_ptr< ::mavlink_common::REQUEST_DATA_STREAM > REQUEST_DATA_STREAMPtr;
typedef boost::shared_ptr< ::mavlink_common::REQUEST_DATA_STREAM const> REQUEST_DATA_STREAMConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07404acd3bbf4b410f00f467a9421990";
  }

  static const char* value(const ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07404acd3bbf4b41ULL;
  static const uint64_t static_value2 = 0x0f00f467a9421990ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/REQUEST_DATA_STREAM";
  }

  static const char* value(const ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.909340\n\
# MESSAGE: REQUEST_DATA_STREAM\n\
uint8 ID = 66\n\
uint8 sysid\n\
uint8 compid\n\
uint8 target_system\n\
uint8 target_component\n\
uint8 req_stream_id\n\
uint16 req_message_rate\n\
uint8 start_stop\n\
";
  }

  static const char* value(const ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.target_system);
      stream.next(m.target_component);
      stream.next(m.req_stream_id);
      stream.next(m.req_message_rate);
      stream.next(m.start_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct REQUEST_DATA_STREAM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::REQUEST_DATA_STREAM_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "target_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_system);
    s << indent << "target_component: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_component);
    s << indent << "req_stream_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.req_stream_id);
    s << indent << "req_message_rate: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.req_message_rate);
    s << indent << "start_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_REQUEST_DATA_STREAM_H
