/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/SAFETY_ALLOWED_AREA.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_SAFETY_ALLOWED_AREA_H
#define MAVLINK_COMMON_MESSAGE_SAFETY_ALLOWED_AREA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct SAFETY_ALLOWED_AREA_
{
  typedef SAFETY_ALLOWED_AREA_<ContainerAllocator> Type;

  SAFETY_ALLOWED_AREA_()
    : sysid(0)
    , compid(0)
    , frame(0)
    , p1x(0.0)
    , p1y(0.0)
    , p1z(0.0)
    , p2x(0.0)
    , p2y(0.0)
    , p2z(0.0)  {
    }
  SAFETY_ALLOWED_AREA_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , frame(0)
    , p1x(0.0)
    , p1y(0.0)
    , p1z(0.0)
    , p2x(0.0)
    , p2y(0.0)
    , p2z(0.0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _frame_type;
  _frame_type frame;

   typedef float _p1x_type;
  _p1x_type p1x;

   typedef float _p1y_type;
  _p1y_type p1y;

   typedef float _p1z_type;
  _p1z_type p1z;

   typedef float _p2x_type;
  _p2x_type p2x;

   typedef float _p2y_type;
  _p2y_type p2y;

   typedef float _p2z_type;
  _p2z_type p2z;


    enum { ID = 55 };
 

  typedef boost::shared_ptr< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SAFETY_ALLOWED_AREA_

typedef ::mavlink_common::SAFETY_ALLOWED_AREA_<std::allocator<void> > SAFETY_ALLOWED_AREA;

typedef boost::shared_ptr< ::mavlink_common::SAFETY_ALLOWED_AREA > SAFETY_ALLOWED_AREAPtr;
typedef boost::shared_ptr< ::mavlink_common::SAFETY_ALLOWED_AREA const> SAFETY_ALLOWED_AREAConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed1a04a3c67e68447c75bbefa087029a";
  }

  static const char* value(const ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed1a04a3c67e6844ULL;
  static const uint64_t static_value2 = 0x7c75bbefa087029aULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/SAFETY_ALLOWED_AREA";
  }

  static const char* value(const ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.908732\n\
# MESSAGE: SAFETY_ALLOWED_AREA\n\
# Description:Read out the safety zone the MAV currently assumes.\n\
uint8 ID = 55\n\
uint8 sysid\n\
uint8 compid\n\
uint8 frame\n\
float32 p1x\n\
float32 p1y\n\
float32 p1z\n\
float32 p2x\n\
float32 p2y\n\
float32 p2z\n\
";
  }

  static const char* value(const ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.frame);
      stream.next(m.p1x);
      stream.next(m.p1y);
      stream.next(m.p1z);
      stream.next(m.p2x);
      stream.next(m.p2y);
      stream.next(m.p2z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SAFETY_ALLOWED_AREA_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::SAFETY_ALLOWED_AREA_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frame);
    s << indent << "p1x: ";
    Printer<float>::stream(s, indent + "  ", v.p1x);
    s << indent << "p1y: ";
    Printer<float>::stream(s, indent + "  ", v.p1y);
    s << indent << "p1z: ";
    Printer<float>::stream(s, indent + "  ", v.p1z);
    s << indent << "p2x: ";
    Printer<float>::stream(s, indent + "  ", v.p2x);
    s << indent << "p2y: ";
    Printer<float>::stream(s, indent + "  ", v.p2y);
    s << indent << "p2z: ";
    Printer<float>::stream(s, indent + "  ", v.p2z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_SAFETY_ALLOWED_AREA_H
