/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/SET_QUAD_MOTORS_SETPOINT.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_SET_QUAD_MOTORS_SETPOINT_H
#define MAVLINK_COMMON_MESSAGE_SET_QUAD_MOTORS_SETPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct SET_QUAD_MOTORS_SETPOINT_
{
  typedef SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> Type;

  SET_QUAD_MOTORS_SETPOINT_()
    : sysid(0)
    , compid(0)
    , target_system(0)
    , motor_front_nw(0)
    , motor_right_ne(0)
    , motor_back_se(0)
    , motor_left_sw(0)  {
    }
  SET_QUAD_MOTORS_SETPOINT_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , target_system(0)
    , motor_front_nw(0)
    , motor_right_ne(0)
    , motor_back_se(0)
    , motor_left_sw(0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _target_system_type;
  _target_system_type target_system;

   typedef uint16_t _motor_front_nw_type;
  _motor_front_nw_type motor_front_nw;

   typedef uint16_t _motor_right_ne_type;
  _motor_right_ne_type motor_right_ne;

   typedef uint16_t _motor_back_se_type;
  _motor_back_se_type motor_back_se;

   typedef uint16_t _motor_left_sw_type;
  _motor_left_sw_type motor_left_sw;


    enum { ID = 60 };
 

  typedef boost::shared_ptr< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SET_QUAD_MOTORS_SETPOINT_

typedef ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<std::allocator<void> > SET_QUAD_MOTORS_SETPOINT;

typedef boost::shared_ptr< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT > SET_QUAD_MOTORS_SETPOINTPtr;
typedef boost::shared_ptr< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT const> SET_QUAD_MOTORS_SETPOINTConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06bbeaab35761779349171359a979245";
  }

  static const char* value(const ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06bbeaab35761779ULL;
  static const uint64_t static_value2 = 0x349171359a979245ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/SET_QUAD_MOTORS_SETPOINT";
  }

  static const char* value(const ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.909038\n\
# MESSAGE: SET_QUAD_MOTORS_SETPOINT\n\
# Description:Setpoint in the four motor speeds\n\
uint8 ID = 60\n\
uint8 sysid\n\
uint8 compid\n\
uint8 target_system\n\
uint16 motor_front_nw\n\
uint16 motor_right_ne\n\
uint16 motor_back_se\n\
uint16 motor_left_sw\n\
";
  }

  static const char* value(const ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.target_system);
      stream.next(m.motor_front_nw);
      stream.next(m.motor_right_ne);
      stream.next(m.motor_back_se);
      stream.next(m.motor_left_sw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SET_QUAD_MOTORS_SETPOINT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::SET_QUAD_MOTORS_SETPOINT_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "target_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_system);
    s << indent << "motor_front_nw: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.motor_front_nw);
    s << indent << "motor_right_ne: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.motor_right_ne);
    s << indent << "motor_back_se: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.motor_back_se);
    s << indent << "motor_left_sw: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.motor_left_sw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_SET_QUAD_MOTORS_SETPOINT_H
