/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_H
#define MAVLINK_COMMON_MESSAGE_SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_
{
  typedef SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> Type;

  SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_()
    : sysid(0)
    , compid(0)
    , group(0)
    , mode(0)
    , roll()
    , pitch()
    , yaw()
    , thrust()  {
      roll.assign(0);

      pitch.assign(0);

      yaw.assign(0);

      thrust.assign(0);
  }
  SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , group(0)
    , mode(0)
    , roll()
    , pitch()
    , yaw()
    , thrust()  {
      roll.assign(0);

      pitch.assign(0);

      yaw.assign(0);

      thrust.assign(0);
  }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _group_type;
  _group_type group;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef boost::array<int16_t, 4>  _roll_type;
  _roll_type roll;

   typedef boost::array<int16_t, 4>  _pitch_type;
  _pitch_type pitch;

   typedef boost::array<int16_t, 4>  _yaw_type;
  _yaw_type yaw;

   typedef boost::array<uint16_t, 4>  _thrust_type;
  _thrust_type thrust;


    enum { ID = 61 };
 

  typedef boost::shared_ptr< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_

typedef ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<std::allocator<void> > SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST;

typedef boost::shared_ptr< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST > SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUSTPtr;
typedef boost::shared_ptr< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST const> SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUSTConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5879dc75137b573705308aab4670d64b";
  }

  static const char* value(const ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5879dc75137b5737ULL;
  static const uint64_t static_value2 = 0x05308aab4670d64bULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST";
  }

  static const char* value(const ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.909097\n\
# MESSAGE: SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST\n\
# Description:Setpoint for up to four quadrotors in a group / wing\n\
uint8 ID = 61\n\
uint8 sysid\n\
uint8 compid\n\
uint8 group\n\
uint8 mode\n\
int16[4] roll\n\
int16[4] pitch\n\
int16[4] yaw\n\
uint16[4] thrust\n\
";
  }

  static const char* value(const ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.group);
      stream.next(m.mode);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.thrust);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "group: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.group);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "roll[]" << std::endl;
    for (size_t i = 0; i < v.roll.size(); ++i)
    {
      s << indent << "  roll[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.roll[i]);
    }
    s << indent << "pitch[]" << std::endl;
    for (size_t i = 0; i < v.pitch.size(); ++i)
    {
      s << indent << "  pitch[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.pitch[i]);
    }
    s << indent << "yaw[]" << std::endl;
    for (size_t i = 0; i < v.yaw.size(); ++i)
    {
      s << indent << "  yaw[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.yaw[i]);
    }
    s << indent << "thrust[]" << std::endl;
    for (size_t i = 0; i < v.thrust.size(); ++i)
    {
      s << indent << "  thrust[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.thrust[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_SET_QUAD_SWARM_ROLL_PITCH_YAW_THRUST_H
