/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/SETPOINT_6DOF.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_SETPOINT_6DOF_H
#define MAVLINK_COMMON_MESSAGE_SETPOINT_6DOF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct SETPOINT_6DOF_
{
  typedef SETPOINT_6DOF_<ContainerAllocator> Type;

  SETPOINT_6DOF_()
    : sysid(0)
    , compid(0)
    , target_system(0)
    , trans_x(0.0)
    , trans_y(0.0)
    , trans_z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)  {
    }
  SETPOINT_6DOF_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , target_system(0)
    , trans_x(0.0)
    , trans_y(0.0)
    , trans_z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _target_system_type;
  _target_system_type target_system;

   typedef float _trans_x_type;
  _trans_x_type trans_x;

   typedef float _trans_y_type;
  _trans_y_type trans_y;

   typedef float _trans_z_type;
  _trans_z_type trans_z;

   typedef float _rot_x_type;
  _rot_x_type rot_x;

   typedef float _rot_y_type;
  _rot_y_type rot_y;

   typedef float _rot_z_type;
  _rot_z_type rot_z;


    enum { ID = 149 };
 

  typedef boost::shared_ptr< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SETPOINT_6DOF_

typedef ::mavlink_common::SETPOINT_6DOF_<std::allocator<void> > SETPOINT_6DOF;

typedef boost::shared_ptr< ::mavlink_common::SETPOINT_6DOF > SETPOINT_6DOFPtr;
typedef boost::shared_ptr< ::mavlink_common::SETPOINT_6DOF const> SETPOINT_6DOFConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e47eab073931fc53905334eb23c9dd58";
  }

  static const char* value(const ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe47eab073931fc53ULL;
  static const uint64_t static_value2 = 0x905334eb23c9dd58ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/SETPOINT_6DOF";
  }

  static const char* value(const ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.910822\n\
# MESSAGE: SETPOINT_6DOF\n\
# Description:Set the 6 DOF setpoint for a attitude and position controller.\n\
uint8 ID = 149\n\
uint8 sysid\n\
uint8 compid\n\
uint8 target_system\n\
float32 trans_x\n\
float32 trans_y\n\
float32 trans_z\n\
float32 rot_x\n\
float32 rot_y\n\
float32 rot_z\n\
";
  }

  static const char* value(const ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.target_system);
      stream.next(m.trans_x);
      stream.next(m.trans_y);
      stream.next(m.trans_z);
      stream.next(m.rot_x);
      stream.next(m.rot_y);
      stream.next(m.rot_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SETPOINT_6DOF_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::SETPOINT_6DOF_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "target_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_system);
    s << indent << "trans_x: ";
    Printer<float>::stream(s, indent + "  ", v.trans_x);
    s << indent << "trans_y: ";
    Printer<float>::stream(s, indent + "  ", v.trans_y);
    s << indent << "trans_z: ";
    Printer<float>::stream(s, indent + "  ", v.trans_z);
    s << indent << "rot_x: ";
    Printer<float>::stream(s, indent + "  ", v.rot_x);
    s << indent << "rot_y: ";
    Printer<float>::stream(s, indent + "  ", v.rot_y);
    s << indent << "rot_z: ";
    Printer<float>::stream(s, indent + "  ", v.rot_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_SETPOINT_6DOF_H
