/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ehang_ws/src/ghost/mavlink_common/msg/VFR_HUD.msg
 *
 */


#ifndef MAVLINK_COMMON_MESSAGE_VFR_HUD_H
#define MAVLINK_COMMON_MESSAGE_VFR_HUD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavlink_common
{
template <class ContainerAllocator>
struct VFR_HUD_
{
  typedef VFR_HUD_<ContainerAllocator> Type;

  VFR_HUD_()
    : sysid(0)
    , compid(0)
    , airspeed(0.0)
    , groundspeed(0.0)
    , heading(0)
    , throttle(0)
    , alt(0.0)
    , climb(0.0)  {
    }
  VFR_HUD_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , airspeed(0.0)
    , groundspeed(0.0)
    , heading(0)
    , throttle(0)
    , alt(0.0)
    , climb(0.0)  {
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef float _airspeed_type;
  _airspeed_type airspeed;

   typedef float _groundspeed_type;
  _groundspeed_type groundspeed;

   typedef int16_t _heading_type;
  _heading_type heading;

   typedef uint16_t _throttle_type;
  _throttle_type throttle;

   typedef float _alt_type;
  _alt_type alt;

   typedef float _climb_type;
  _climb_type climb;


    enum { ID = 74 };
 

  typedef boost::shared_ptr< ::mavlink_common::VFR_HUD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavlink_common::VFR_HUD_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct VFR_HUD_

typedef ::mavlink_common::VFR_HUD_<std::allocator<void> > VFR_HUD;

typedef boost::shared_ptr< ::mavlink_common::VFR_HUD > VFR_HUDPtr;
typedef boost::shared_ptr< ::mavlink_common::VFR_HUD const> VFR_HUDConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavlink_common::VFR_HUD_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavlink_common::VFR_HUD_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavlink_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mavlink_common': ['/root/ehang_ws/src/ghost/mavlink_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::VFR_HUD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavlink_common::VFR_HUD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::VFR_HUD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavlink_common::VFR_HUD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::VFR_HUD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavlink_common::VFR_HUD_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavlink_common::VFR_HUD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea8310914fe29188775b58af6e062e84";
  }

  static const char* value(const ::mavlink_common::VFR_HUD_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea8310914fe29188ULL;
  static const uint64_t static_value2 = 0x775b58af6e062e84ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavlink_common::VFR_HUD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavlink_common/VFR_HUD";
  }

  static const char* value(const ::mavlink_common::VFR_HUD_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavlink_common::VFR_HUD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2014-08-12 13:24:39.909567\n\
# MESSAGE: VFR_HUD\n\
# Description:Metrics typically displayed on a HUD for fixed wing aircraft\n\
uint8 ID = 74\n\
uint8 sysid\n\
uint8 compid\n\
float32 airspeed\n\
float32 groundspeed\n\
int16 heading\n\
uint16 throttle\n\
float32 alt\n\
float32 climb\n\
";
  }

  static const char* value(const ::mavlink_common::VFR_HUD_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavlink_common::VFR_HUD_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.airspeed);
      stream.next(m.groundspeed);
      stream.next(m.heading);
      stream.next(m.throttle);
      stream.next(m.alt);
      stream.next(m.climb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct VFR_HUD_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavlink_common::VFR_HUD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavlink_common::VFR_HUD_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "airspeed: ";
    Printer<float>::stream(s, indent + "  ", v.airspeed);
    s << indent << "groundspeed: ";
    Printer<float>::stream(s, indent + "  ", v.groundspeed);
    s << indent << "heading: ";
    Printer<int16_t>::stream(s, indent + "  ", v.heading);
    s << indent << "throttle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.throttle);
    s << indent << "alt: ";
    Printer<float>::stream(s, indent + "  ", v.alt);
    s << indent << "climb: ";
    Printer<float>::stream(s, indent + "  ", v.climb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVLINK_COMMON_MESSAGE_VFR_HUD_H
